"""Build script for Bytehound Single-Cell BMS Cycler executable using PyInstaller.

Usage:
    python single_cell_cycler/build.py              # Clean + Build (onedir) + Zip
    python single_cell_cycler/build.py --onefile    # Build single standalone .exe
    python single_cell_cycler/build.py --console    # Build with debug console window
    python single_cell_cycler/build.py --no-clean   # Incremental build without wiping dist/
    python single_cell_cycler/build.py --no-zip     # Skip creating the distribution .zip

Output:
    dist/SingleCellCycler/SingleCellCycler.exe       (onedir bundle)
    dist/SingleCellCycler_v1.0.0_win64.zip          (distributable release archive)
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path
import zipfile

# Resolve repository paths
SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
APP_NAME = "SingleCellCycler"
MAIN_ENTRY = SCRIPT_DIR / "main.py"
SPEC_FILE = SCRIPT_DIR / "SingleCellCycler.spec"
DIST_DIR = REPO_ROOT / "dist"
BUILD_DIR = REPO_ROOT / "build" / APP_NAME
OUTPUT_DIR = DIST_DIR / APP_NAME
BRANDING_DIR = REPO_ROOT / "branding"
ICON_PATH = BRANDING_DIR / "logo.ico"


def get_app_version() -> str:
    """Read version from version.json in repo root or fallback to 1.0.0."""
    ver_file = REPO_ROOT / "version.json"
    if ver_file.exists():
        try:
            with open(ver_file, "r", encoding="utf-8") as f:
                data = json.load(f)
                return str(data.get("version", "1.0.0"))
        except Exception:
            pass
    return "1.0.0"


def clean_artifacts() -> None:
    """Clean previous build and dist directories."""
    print(f"[build] Cleaning previous build artifacts...")
    for target in (OUTPUT_DIR, BUILD_DIR):
        if target.exists():
            print(f"  Removing {target}")
            try:
                shutil.rmtree(target, ignore_errors=True)
            except Exception as e:
                print(f"  [warn] Could not remove {target}: {e}")


def generate_spec_file(onefile: bool = False, console: bool = False) -> Path:
    """Generate a high-performance PyInstaller .spec file tailored for Single-Cell Cycler."""
    has_icon = ICON_PATH.exists()
    icon_entry = f"icon=r'{ICON_PATH.resolve()}'," if has_icon else "icon=None,"

    spec_content = f"""# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by single_cell_cycler/build.py

import os
import sys
from pathlib import Path
from PyInstaller.utils.hooks import collect_all

block_cipher = None

repo_root = Path(r'{REPO_ROOT.resolve()}')
cycler_root = repo_root / 'single_cell_cycler'

# Core Data Files & Standard Recipes
datas = [
    (str(cycler_root / 'config' / 'recipes'), 'single_cell_cycler/config/recipes'),
]

# Include branding if present
branding_path = repo_root / 'branding'
if branding_path.exists():
    datas.append((str(branding_path), 'branding'))

version_json = repo_root / 'version.json'
if version_json.exists():
    datas.append((str(version_json), '.'))

binaries = []
hiddenimports = [
    'pyqtgraph',
    'numpy',
    'serial',
    'serial.tools',
    'serial.tools.list_ports',
    'PySide6.QtCore',
    'PySide6.QtGui',
    'PySide6.QtWidgets',
]

# Collect PySide6 & shiboken6 runtime bindings
raw_datas, raw_binaries, raw_hidden = collect_all('PySide6')
datas += raw_datas
binaries += raw_binaries
hiddenimports += raw_hidden

# Massive unused modules to exclude to keep build fast, lean and clean (< 70 MB)
excluded_modules = [
    'torch', 'scipy', 'matplotlib', 'sympy', 'IPython', 'tornado', 'twisted',
    'PIL', 'lxml', 'pygments', 'tensorflow', 'coremltools', 'pytorch_lightning',
    'jinja2', 'jedi', 'psutil', 'pandas', 'openpyxl',
    'PySide6.QtWebEngineCore', 'PySide6.QtWebEngineQuick', 'PySide6.QtWebEngine',
    'PySide6.Qt3DCore', 'PySide6.Qt3DRender', 'PySide6.Qt3DInput', 'PySide6.Qt3DLogic',
    'PySide6.QtMultimedia', 'PySide6.QtMultimediaWidgets', 'PySide6.QtCharts',
    'PySide6.QtDataVisualization', 'PySide6.QtQuick', 'PySide6.QtQuickWidgets',
    'PySide6.QtQml', 'PySide6.QtRemoteObjects', 'PySide6.QtSensors', 'PySide6.QtSerialBus',
    'PySide6.QtPositioning', 'PySide6.QtBluetooth', 'PySide6.QtNfc', 'PySide6.QtWebChannel',
    'PySide6.QtWebSockets', 'PySide6.QtSql', 'PySide6.QtTest', 'PySide6.QtXmlPatterns',
    'PySide6.QtTextToSpeech', 'PySide6.QtLocation', 'PySide6.QtSpatialAudio', 'PySide6.QtDesigner',
]

a = Analysis(
    [r'{MAIN_ENTRY.resolve()}'],
    pathex=[str(repo_root)],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=excluded_modules,
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

{"exe = EXE(" if onefile else "exe = EXE("}
    pyz,
    a.scripts,
    {"a.binaries, a.zipfiles, a.datas," if onefile else "[],"}
    exclude_binaries={not onefile},
    name='{APP_NAME}',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console={console},
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    {icon_entry}
)

{"# Onefile build completes at EXE" if onefile else f'''coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='{APP_NAME}',
)'''}
"""
    SPEC_FILE.write_text(spec_content, encoding="utf-8")
    print(f"[build] Generated PyInstaller spec: {SPEC_FILE.name}")
    return SPEC_FILE


def run_build(spec_path: Path) -> int:
    """Execute PyInstaller build."""
    cmd = [
        sys.executable,
        "-m",
        "PyInstaller",
        "--noconfirm",
        f"--distpath={DIST_DIR}",
        f"--workpath={REPO_ROOT / 'build'}",
        str(spec_path),
    ]
    print(f"[build] Executing: {' '.join(cmd)}")
    t0 = time.time()
    res = subprocess.call(cmd, cwd=REPO_ROOT)
    t1 = time.time()
    if res == 0:
        print(f"[build] PyInstaller compilation completed in {t1 - t0:.1f}s")
    else:
        print(f"[build] [ERROR] PyInstaller compilation failed with code {res}")
    return res


def create_distribution_zip(version: str, onefile: bool) -> Path:
    """Zip the output bundle for distribution."""
    zip_name = f"{APP_NAME}_v{version}_win64.zip"
    zip_path = DIST_DIR / zip_name
    print(f"[build] Creating release archive: {zip_path.name}...")

    if onefile:
        exe_file = DIST_DIR / f"{APP_NAME}.exe"
        if not exe_file.exists():
            raise FileNotFoundError(f"Expected binary {exe_file} not found")
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            zf.write(exe_file, arcname=exe_file.name)
            # Add recipe templates
            recipes_dir = SCRIPT_DIR / "config" / "recipes"
            if recipes_dir.exists():
                for r in recipes_dir.glob("*.json"):
                    zf.write(r, arcname=f"recipes/{r.name}")
    else:
        if not OUTPUT_DIR.exists():
            raise FileNotFoundError(f"Expected directory {OUTPUT_DIR} not found")
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            for root, _, files in os.walk(OUTPUT_DIR):
                for file in files:
                    file_path = Path(root) / file
                    rel_path = file_path.relative_to(DIST_DIR)
                    zf.write(file_path, arcname=str(rel_path))

    size_mb = zip_path.stat().st_size / (1024 * 1024)
    print(f"[build] Release archive created successfully: {zip_path} ({size_mb:.1f} MB)")
    return zip_path


def main() -> int:
    parser = argparse.ArgumentParser(description="Build Single-Cell BMS Cycler executable.")
    parser.add_argument("--onefile", action="store_true", help="Build as a single standalone .exe")
    parser.add_argument("--console", action="store_true", help="Keep console window open (debug mode)")
    parser.add_argument("--no-clean", action="store_true", help="Do not wipe dist/ and build/ before building")
    parser.add_argument("--no-zip", action="store_true", help="Skip creating release zip archive")
    parser.add_argument("--spec-only", action="store_true", help="Generate the .spec file without building")
    args = parser.parse_args()

    version = get_app_version()
    print("=" * 65)
    print(f"   BYTEHOUND SINGLE-CELL BMS CYCLER BUILD TOOL (v{version})")
    print("=" * 65)
    print(f"Target Binary : {APP_NAME}.exe ({'Onefile' if args.onefile else 'Onedir'})")
    print(f"Console Mode  : {'Enabled (Debug)' if args.console else 'Disabled (Windowed)'}")
    print(f"Repository    : {REPO_ROOT}")

    if not args.no_clean and not args.spec_only:
        clean_artifacts()

    # Ensure output dist directory exists
    DIST_DIR.mkdir(parents=True, exist_ok=True)

    spec_path = generate_spec_file(onefile=args.onefile, console=args.console)
    if args.spec_only:
        print("[build] Spec file generated. Exiting due to --spec-only flag.")
        return 0

    build_code = run_build(spec_path)
    if build_code != 0:
        return build_code

    # Verify build results
    target_exe = (DIST_DIR / f"{APP_NAME}.exe") if args.onefile else (OUTPUT_DIR / f"{APP_NAME}.exe")
    if not target_exe.exists():
        print(f"[build] [ERROR] Expected executable {target_exe} was not produced!")
        return 1

    print("\n" + "=" * 65)
    print(f"   BUILD SUCCEEDED: {target_exe.name}")
    print(f"   Executable Location: {target_exe}")
    print("=" * 65)

    if not args.no_zip:
        create_distribution_zip(version, onefile=args.onefile)

    print("\n[build] All build steps completed successfully!")
    print(f"Run the application with: {target_exe}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
