# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by single_cell_cycler/build.py

import os
import sys
from pathlib import Path
from PyInstaller.utils.hooks import collect_all

block_cipher = None

repo_root = Path(r'C:\Users\Shreyas\Documents\Python\Bytehound')
cycler_root = repo_root / 'single_cell_cycler'

# Core Data Files & Standard Recipes
datas = [
    (str(cycler_root / 'config' / 'recipes'), 'single_cell_cycler/config/recipes'),
]

# Include branding if present
branding_path = repo_root / 'branding'
if branding_path.exists():
    datas.append((str(branding_path), 'branding'))

version_json = repo_root / 'version.json'
if version_json.exists():
    datas.append((str(version_json), '.'))

binaries = []
hiddenimports = [
    'pyqtgraph',
    'numpy',
    'serial',
    'serial.tools',
    'serial.tools.list_ports',
    'PySide6.QtCore',
    'PySide6.QtGui',
    'PySide6.QtWidgets',
]

# Collect PySide6 & shiboken6 runtime bindings
raw_datas, raw_binaries, raw_hidden = collect_all('PySide6')
datas += raw_datas
binaries += raw_binaries
hiddenimports += raw_hidden

# Massive unused modules to exclude to keep build fast, lean and clean (< 70 MB)
excluded_modules = [
    'torch', 'scipy', 'matplotlib', 'sympy', 'IPython', 'tornado', 'twisted',
    'PIL', 'lxml', 'pygments', 'tensorflow', 'coremltools', 'pytorch_lightning',
    'jinja2', 'jedi', 'psutil', 'pandas', 'openpyxl',
    'PySide6.QtWebEngineCore', 'PySide6.QtWebEngineQuick', 'PySide6.QtWebEngine',
    'PySide6.Qt3DCore', 'PySide6.Qt3DRender', 'PySide6.Qt3DInput', 'PySide6.Qt3DLogic',
    'PySide6.QtMultimedia', 'PySide6.QtMultimediaWidgets', 'PySide6.QtCharts',
    'PySide6.QtDataVisualization', 'PySide6.QtQuick', 'PySide6.QtQuickWidgets',
    'PySide6.QtQml', 'PySide6.QtRemoteObjects', 'PySide6.QtSensors', 'PySide6.QtSerialBus',
    'PySide6.QtPositioning', 'PySide6.QtBluetooth', 'PySide6.QtNfc', 'PySide6.QtWebChannel',
    'PySide6.QtWebSockets', 'PySide6.QtSql', 'PySide6.QtTest', 'PySide6.QtXmlPatterns',
    'PySide6.QtTextToSpeech', 'PySide6.QtLocation', 'PySide6.QtSpatialAudio', 'PySide6.QtDesigner',
]

a = Analysis(
    [r'C:\Users\Shreyas\Documents\Python\Bytehound\single_cell_cycler\main.py'],
    pathex=[str(repo_root)],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excluded_modules,
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='SingleCellCycler',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=r'C:\Users\Shreyas\Documents\Python\Bytehound\branding\logo.ico',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='SingleCellCycler',
)
