/*
 * Copyright 2018-2020, 2024 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * @file      siul_private.h
 * @brief     System Integration Unit Lite2 (SIUL) private definitions.
 */
#ifndef __SIUL_PRIVATE_H
#define __SIUL_PRIVATE_H

/******************************************************************************
 * Alliases for IO registers
 ******************************************************************************/
#define PTA_PIN0_GPDO(slot)  prvVSIUL[slot]->GPDO0
#define PTA_PIN0_GPDI(slot)  prvVSIUL[slot]->GPDI0
#define PTA_PIN1_GPDO(slot)  prvVSIUL[slot]->GPDO1
#define PTA_PIN1_GPDI(slot)  prvVSIUL[slot]->GPDI1
#define PTA_PIN2_GPDO(slot)  prvVSIUL[slot]->GPDO2
#define PTA_PIN2_GPDI(slot)  prvVSIUL[slot]->GPDI2
#define PTA_PIN3_GPDO(slot)  prvVSIUL[slot]->GPDO3
#define PTA_PIN3_GPDI(slot)  prvVSIUL[slot]->GPDI3
#define PTA_PIN4_GPDO(slot)  prvVSIUL[slot]->GPDO4
#define PTA_PIN4_GPDI(slot)  prvVSIUL[slot]->GPDI4
#define PTA_PIN5_GPDO(slot)  prvVSIUL[slot]->GPDO5
#define PTA_PIN5_GPDI(slot)  prvVSIUL[slot]->GPDI5
#define PTA_PIN6_GPDO(slot)  prvVSIUL[slot]->GPDO6
#define PTA_PIN6_GPDI(slot)  prvVSIUL[slot]->GPDI6
#define PTA_PIN7_GPDO(slot)  prvVSIUL[slot]->GPDO7
#define PTA_PIN7_GPDI(slot)  prvVSIUL[slot]->GPDI7
#define PTA_PIN8_GPDO(slot)  prvVSIUL[slot]->GPDO8
#define PTA_PIN8_GPDI(slot)  prvVSIUL[slot]->GPDI8
#define PTA_PIN9_GPDO(slot)  prvVSIUL[slot]->GPDO9
#define PTA_PIN9_GPDI(slot)  prvVSIUL[slot]->GPDI9
#define PTA_PIN10_GPDO(slot) prvVSIUL[slot]->GPDO10
#define PTA_PIN10_GPDI(slot) prvVSIUL[slot]->GPDI10
#define PTA_PIN11_GPDO(slot) prvVSIUL[slot]->GPDO11
#define PTA_PIN11_GPDI(slot) prvVSIUL[slot]->GPDI11
#define PTA_PIN12_GPDO(slot) prvVSIUL[slot]->GPDO12
#define PTA_PIN12_GPDI(slot) prvVSIUL[slot]->GPDI12
#define PTA_PIN13_GPDO(slot) prvVSIUL[slot]->GPDO13
#define PTA_PIN13_GPDI(slot) prvVSIUL[slot]->GPDI13
#define PTA_PIN14_GPDO(slot) prvVSIUL[slot]->GPDO14
#define PTA_PIN14_GPDI(slot) prvVSIUL[slot]->GPDI14
#define PTA_PIN15_GPDO(slot) prvVSIUL[slot]->GPDO15
#define PTA_PIN15_GPDI(slot) prvVSIUL[slot]->GPDI15
#define PTA_PIN16_GPDO(slot) prvVSIUL[slot]->GPDO16
#define PTA_PIN16_GPDI(slot) prvVSIUL[slot]->GPDI16
#define PTA_PIN17_GPDO(slot) prvVSIUL[slot]->GPDO17
#define PTA_PIN17_GPDI(slot) prvVSIUL[slot]->GPDI17
#define PTA_PIN18_GPDO(slot) prvVSIUL[slot]->GPDO18
#define PTA_PIN18_GPDI(slot) prvVSIUL[slot]->GPDI18
#define PTA_PIN19_GPDO(slot) prvVSIUL[slot]->GPDO19
#define PTA_PIN19_GPDI(slot) prvVSIUL[slot]->GPDI19
#define PTA_PIN20_GPDO(slot) prvVSIUL[slot]->GPDO20
#define PTA_PIN20_GPDI(slot) prvVSIUL[slot]->GPDI20
#define PTA_PIN21_GPDO(slot) prvVSIUL[slot]->GPDO21
#define PTA_PIN21_GPDI(slot) prvVSIUL[slot]->GPDI21
#define PTA_PIN22_GPDO(slot) prvVSIUL[slot]->GPDO22
#define PTA_PIN22_GPDI(slot) prvVSIUL[slot]->GPDI22
#define PTA_PIN23_GPDO(slot) prvVSIUL[slot]->GPDO23
#define PTA_PIN23_GPDI(slot) prvVSIUL[slot]->GPDI23
#define PTA_PIN26_GPDO(slot) prvVSIUL[slot]->GPDO26
#define PTA_PIN26_GPDI(slot) prvVSIUL[slot]->GPDI26
#define PTA_PIN27_GPDO(slot) prvVSIUL[slot]->GPDO27
#define PTA_PIN27_GPDI(slot) prvVSIUL[slot]->GPDI27
#define PTA_PIN28_GPDO(slot) prvVSIUL[slot]->GPDO28
#define PTA_PIN28_GPDI(slot) prvVSIUL[slot]->GPDI28
#define PTA_PIN29_GPDO(slot) prvVSIUL[slot]->GPDO29
#define PTA_PIN29_GPDI(slot) prvVSIUL[slot]->GPDI29
#define PTA_PIN30_GPDO(slot) prvVSIUL[slot]->GPDO30
#define PTA_PIN30_GPDI(slot) prvVSIUL[slot]->GPDI30
#define PTA_PIN31_GPDO(slot) prvVSIUL[slot]->GPDO31
#define PTA_PIN31_GPDI(slot) prvVSIUL[slot]->GPDI31
#define PTB_PIN0_GPDO(slot)  prvVSIUL[slot]->GPDO32
#define PTB_PIN0_GPDI(slot)  prvVSIUL[slot]->GPDI32
#define PTB_PIN1_GPDO(slot)  prvVSIUL[slot]->GPDO33
#define PTB_PIN1_GPDI(slot)  prvVSIUL[slot]->GPDI33
#define PTB_PIN2_GPDO(slot)  prvVSIUL[slot]->GPDO34
#define PTB_PIN2_GPDI(slot)  prvVSIUL[slot]->GPDI34
#define PTB_PIN3_GPDO(slot)  prvVSIUL[slot]->GPDO35
#define PTB_PIN3_GPDI(slot)  prvVSIUL[slot]->GPDI35
#define PTB_PIN4_GPDO(slot)  prvVSIUL[slot]->GPDO36
#define PTB_PIN4_GPDI(slot)  prvVSIUL[slot]->GPDI36
#define PTB_PIN5_GPDO(slot)  prvVSIUL[slot]->GPDO37
#define PTB_PIN5_GPDI(slot)  prvVSIUL[slot]->GPDI37
#define PTB_PIN8_GPDO(slot)  prvVSIUL[slot]->GPDO40
#define PTB_PIN8_GPDI(slot)  prvVSIUL[slot]->GPDI40
#define PTB_PIN9_GPDO(slot)  prvVSIUL[slot]->GPDO41
#define PTB_PIN9_GPDI(slot)  prvVSIUL[slot]->GPDI41
#define PTB_PIN10_GPDO(slot) prvVSIUL[slot]->GPDO42
#define PTB_PIN10_GPDI(slot) prvVSIUL[slot]->GPDI42
#define PTB_PIN11_GPDO(slot) prvVSIUL[slot]->GPDO43
#define PTB_PIN11_GPDI(slot) prvVSIUL[slot]->GPDI43
#define PTB_PIN12_GPDO(slot) prvVSIUL[slot]->GPDO44
#define PTB_PIN12_GPDI(slot) prvVSIUL[slot]->GPDI44
#define PTB_PIN13_GPDO(slot) prvVSIUL[slot]->GPDO45
#define PTB_PIN13_GPDI(slot) prvVSIUL[slot]->GPDI45
#define PTB_PIN14_GPDO(slot) prvVSIUL[slot]->GPDO46
#define PTB_PIN14_GPDI(slot) prvVSIUL[slot]->GPDI46
#define PTB_PIN15_GPDO(slot) prvVSIUL[slot]->GPDO47
#define PTB_PIN15_GPDI(slot) prvVSIUL[slot]->GPDI47
#define PTB_PIN16_GPDO(slot) prvVSIUL[slot]->GPDO48
#define PTB_PIN16_GPDI(slot) prvVSIUL[slot]->GPDI48
#define PTB_PIN17_GPDO(slot) prvVSIUL[slot]->GPDO49
#define PTB_PIN17_GPDI(slot) prvVSIUL[slot]->GPDI49
#define PTB_PIN18_GPDO(slot) prvVSIUL[slot]->GPDO50
#define PTB_PIN18_GPDI(slot) prvVSIUL[slot]->GPDI50
#define PTB_PIN19_GPDO(slot) prvVSIUL[slot]->GPDO51
#define PTB_PIN19_GPDI(slot) prvVSIUL[slot]->GPDI51
#define PTB_PIN20_GPDO(slot) prvVSIUL[slot]->GPDO52
#define PTB_PIN20_GPDI(slot) prvVSIUL[slot]->GPDI52
#define PTB_PIN21_GPDO(slot) prvVSIUL[slot]->GPDO53
#define PTB_PIN21_GPDI(slot) prvVSIUL[slot]->GPDI53
#define PTB_PIN22_GPDO(slot) prvVSIUL[slot]->GPDO54
#define PTB_PIN22_GPDI(slot) prvVSIUL[slot]->GPDI54
#define PTB_PIN23_GPDO(slot) prvVSIUL[slot]->GPDO55
#define PTB_PIN23_GPDI(slot) prvVSIUL[slot]->GPDI55
#define PTB_PIN24_GPDO(slot) prvVSIUL[slot]->GPDO56
#define PTB_PIN24_GPDI(slot) prvVSIUL[slot]->GPDI56
#define PTB_PIN25_GPDO(slot) prvVSIUL[slot]->GPDO57
#define PTB_PIN25_GPDI(slot) prvVSIUL[slot]->GPDI57
#define PTB_PIN26_GPDO(slot) prvVSIUL[slot]->GPDO58
#define PTB_PIN26_GPDI(slot) prvVSIUL[slot]->GPDI58
#define PTB_PIN27_GPDO(slot) prvVSIUL[slot]->GPDO59
#define PTB_PIN27_GPDI(slot) prvVSIUL[slot]->GPDI59
#define PTB_PIN28_GPDO(slot) prvVSIUL[slot]->GPDO60
#define PTB_PIN28_GPDI(slot) prvVSIUL[slot]->GPDI60
#define PTB_PIN29_GPDO(slot) prvVSIUL[slot]->GPDO61
#define PTB_PIN29_GPDI(slot) prvVSIUL[slot]->GPDI61
#define PTB_PIN30_GPDO(slot) prvVSIUL[slot]->GPDO62
#define PTB_PIN30_GPDI(slot) prvVSIUL[slot]->GPDI62
#define PTB_PIN31_GPDO(slot) prvVSIUL[slot]->GPDO63
#define PTB_PIN31_GPDI(slot) prvVSIUL[slot]->GPDI63
#define PTC_PIN0_GPDO(slot)  prvVSIUL[slot]->GPDO64
#define PTC_PIN0_GPDI(slot)  prvVSIUL[slot]->GPDI64
#define PTC_PIN1_GPDO(slot)  prvVSIUL[slot]->GPDO65
#define PTC_PIN1_GPDI(slot)  prvVSIUL[slot]->GPDI65
#define PTC_PIN2_GPDO(slot)  prvVSIUL[slot]->GPDO66
#define PTC_PIN2_GPDI(slot)  prvVSIUL[slot]->GPDI66
#define PTC_PIN3_GPDO(slot)  prvVSIUL[slot]->GPDO67
#define PTC_PIN3_GPDI(slot)  prvVSIUL[slot]->GPDI67
#define PTC_PIN4_GPDO(slot)  prvVSIUL[slot]->GPDO68
#define PTC_PIN4_GPDI(slot)  prvVSIUL[slot]->GPDI68
#define PTC_PIN5_GPDO(slot)  prvVSIUL[slot]->GPDO69
#define PTC_PIN5_GPDI(slot)  prvVSIUL[slot]->GPDI69
#define PTC_PIN6_GPDO(slot)  prvVSIUL[slot]->GPDO70
#define PTC_PIN6_GPDI(slot)  prvVSIUL[slot]->GPDI70
#define PTC_PIN7_GPDO(slot)  prvVSIUL[slot]->GPDO71
#define PTC_PIN7_GPDI(slot)  prvVSIUL[slot]->GPDI71
#define PTC_PIN8_GPDO(slot)  prvVSIUL[slot]->GPDO72
#define PTC_PIN8_GPDI(slot)  prvVSIUL[slot]->GPDI72
#define PTC_PIN9_GPDO(slot)  prvVSIUL[slot]->GPDO73
#define PTC_PIN9_GPDI(slot)  prvVSIUL[slot]->GPDI73
#define PTC_PIN10_GPDO(slot) prvVSIUL[slot]->GPDO74
#define PTC_PIN10_GPDI(slot) prvVSIUL[slot]->GPDI74
#define PTC_PIN11_GPDO(slot) prvVSIUL[slot]->GPDO75
#define PTC_PIN11_GPDI(slot) prvVSIUL[slot]->GPDI75
#define PTC_PIN12_GPDO(slot) prvVSIUL[slot]->GPDO76
#define PTC_PIN12_GPDI(slot) prvVSIUL[slot]->GPDI76
#define PTC_PIN13_GPDO(slot) prvVSIUL[slot]->GPDO77
#define PTC_PIN13_GPDI(slot) prvVSIUL[slot]->GPDI77
#define PTC_PIN14_GPDO(slot) prvVSIUL[slot]->GPDO78
#define PTC_PIN14_GPDI(slot) prvVSIUL[slot]->GPDI78
#define PTC_PIN15_GPDO(slot) prvVSIUL[slot]->GPDO79
#define PTC_PIN15_GPDI(slot) prvVSIUL[slot]->GPDI79
#define PTC_PIN16_GPDO(slot) prvVSIUL[slot]->GPDO80
#define PTC_PIN16_GPDI(slot) prvVSIUL[slot]->GPDI80
#define PTC_PIN17_GPDO(slot) prvVSIUL[slot]->GPDO81
#define PTC_PIN17_GPDI(slot) prvVSIUL[slot]->GPDI81
#define PTC_PIN18_GPDO(slot) prvVSIUL[slot]->GPDO82
#define PTC_PIN18_GPDI(slot) prvVSIUL[slot]->GPDI82
#define PTC_PIN19_GPDO(slot) prvVSIUL[slot]->GPDO83
#define PTC_PIN19_GPDI(slot) prvVSIUL[slot]->GPDI83
#define PTC_PIN20_GPDO(slot) prvVSIUL[slot]->GPDO84
#define PTC_PIN20_GPDI(slot) prvVSIUL[slot]->GPDI84
#define PTC_PIN21_GPDO(slot) prvVSIUL[slot]->GPDO85
#define PTC_PIN21_GPDI(slot) prvVSIUL[slot]->GPDI85
#define PTC_PIN22_GPDO(slot) prvVSIUL[slot]->GPDO86
#define PTC_PIN22_GPDI(slot) prvVSIUL[slot]->GPDI86
#define PTC_PIN23_GPDO(slot) prvVSIUL[slot]->GPDO87
#define PTC_PIN23_GPDI(slot) prvVSIUL[slot]->GPDI87
#define PTC_PIN24_GPDO(slot) prvVSIUL[slot]->GPDO88
#define PTC_PIN24_GPDI(slot) prvVSIUL[slot]->GPDI88
#define PTC_PIN25_GPDO(slot) prvVSIUL[slot]->GPDO89
#define PTC_PIN25_GPDI(slot) prvVSIUL[slot]->GPDI89
#define PTC_PIN26_GPDO(slot) prvVSIUL[slot]->GPDO90
#define PTC_PIN26_GPDI(slot) prvVSIUL[slot]->GPDI90
#define PTC_PIN27_GPDO(slot) prvVSIUL[slot]->GPDO91
#define PTC_PIN27_GPDI(slot) prvVSIUL[slot]->GPDI91
#define PTC_PIN28_GPDO(slot) prvVSIUL[slot]->GPDO92
#define PTC_PIN28_GPDI(slot) prvVSIUL[slot]->GPDI92
#define PTC_PIN29_GPDO(slot) prvVSIUL[slot]->GPDO93
#define PTC_PIN29_GPDI(slot) prvVSIUL[slot]->GPDI93
#define PTC_PIN30_GPDO(slot) prvVSIUL[slot]->GPDO94
#define PTC_PIN30_GPDI(slot) prvVSIUL[slot]->GPDI94
#define PTC_PIN31_GPDO(slot) prvVSIUL[slot]->GPDO95
#define PTC_PIN31_GPDI(slot) prvVSIUL[slot]->GPDI95
#define PTD_PIN0_GPDO(slot)  prvVSIUL[slot]->GPDO96
#define PTD_PIN0_GPDI(slot)  prvVSIUL[slot]->GPDI96
#define PTD_PIN1_GPDO(slot)  prvVSIUL[slot]->GPDO97
#define PTD_PIN1_GPDI(slot)  prvVSIUL[slot]->GPDI97
#define PTD_PIN2_GPDO(slot)  prvVSIUL[slot]->GPDO98
#define PTD_PIN2_GPDI(slot)  prvVSIUL[slot]->GPDI98
#define PTD_PIN3_GPDO(slot)  prvVSIUL[slot]->GPDO99
#define PTD_PIN3_GPDI(slot)  prvVSIUL[slot]->GPDI99
#define PTD_PIN4_GPDO(slot)  prvVSIUL[slot]->GPDO100
#define PTD_PIN4_GPDI(slot)  prvVSIUL[slot]->GPDI100
#define PTD_PIN5_GPDO(slot)  prvVSIUL[slot]->GPDO101
#define PTD_PIN5_GPDI(slot)  prvVSIUL[slot]->GPDI101
#define PTD_PIN6_GPDO(slot)  prvVSIUL[slot]->GPDO102
#define PTD_PIN6_GPDI(slot)  prvVSIUL[slot]->GPDI102
#define PTD_PIN7_GPDO(slot)  prvVSIUL[slot]->GPDO103
#define PTD_PIN7_GPDI(slot)  prvVSIUL[slot]->GPDI103
#define PTD_PIN8_GPDO(slot)  prvVSIUL[slot]->GPDO104
#define PTD_PIN8_GPDI(slot)  prvVSIUL[slot]->GPDI104
#define PTD_PIN9_GPDO(slot)  prvVSIUL[slot]->GPDO105
#define PTD_PIN9_GPDI(slot)  prvVSIUL[slot]->GPDI105
#define PTD_PIN10_GPDO(slot) prvVSIUL[slot]->GPDO106
#define PTD_PIN10_GPDI(slot) prvVSIUL[slot]->GPDI106
#define PTD_PIN11_GPDO(slot) prvVSIUL[slot]->GPDO107
#define PTD_PIN11_GPDI(slot) prvVSIUL[slot]->GPDI107
#define PTD_PIN12_GPDO(slot) prvVSIUL[slot]->GPDO108
#define PTD_PIN12_GPDI(slot) prvVSIUL[slot]->GPDI108
#define PTD_PIN13_GPDO(slot) prvVSIUL[slot]->GPDO109
#define PTD_PIN13_GPDI(slot) prvVSIUL[slot]->GPDI109
#define PTD_PIN14_GPDO(slot) prvVSIUL[slot]->GPDO110
#define PTD_PIN14_GPDI(slot) prvVSIUL[slot]->GPDI110
#define PTD_PIN15_GPDO(slot) prvVSIUL[slot]->GPDO111
#define PTD_PIN15_GPDI(slot) prvVSIUL[slot]->GPDI111
#define PTD_PIN16_GPDO(slot) prvVSIUL[slot]->GPDO112
#define PTD_PIN16_GPDI(slot) prvVSIUL[slot]->GPDI112
#define PTD_PIN17_GPDO(slot) prvVSIUL[slot]->GPDO113
#define PTD_PIN17_GPDI(slot) prvVSIUL[slot]->GPDI113
#define PTD_PIN18_GPDO(slot) prvVSIUL[slot]->GPDO114
#define PTD_PIN18_GPDI(slot) prvVSIUL[slot]->GPDI114
#define PTD_PIN19_GPDO(slot) prvVSIUL[slot]->GPDO115
#define PTD_PIN19_GPDI(slot) prvVSIUL[slot]->GPDI115
#define PTD_PIN20_GPDO(slot) prvVSIUL[slot]->GPDO116
#define PTD_PIN20_GPDI(slot) prvVSIUL[slot]->GPDI116
#define PTD_PIN21_GPDO(slot) prvVSIUL[slot]->GPDO117
#define PTD_PIN21_GPDI(slot) prvVSIUL[slot]->GPDI117
#define PTD_PIN22_GPDO(slot) prvVSIUL[slot]->GPDO118
#define PTD_PIN22_GPDI(slot) prvVSIUL[slot]->GPDI118
#define PTD_PIN23_GPDO(slot) prvVSIUL[slot]->GPDO119
#define PTD_PIN23_GPDI(slot) prvVSIUL[slot]->GPDI119
#define PTD_PIN24_GPDO(slot) prvVSIUL[slot]->GPDO120
#define PTD_PIN24_GPDI(slot) prvVSIUL[slot]->GPDI120
#define PTD_PIN25_GPDO(slot) prvVSIUL[slot]->GPDO121
#define PTD_PIN25_GPDI(slot) prvVSIUL[slot]->GPDI121
#define PTD_PIN26_GPDO(slot) prvVSIUL[slot]->GPDO122
#define PTD_PIN26_GPDI(slot) prvVSIUL[slot]->GPDI122
#define PTD_PIN27_GPDO(slot) prvVSIUL[slot]->GPDO123
#define PTD_PIN27_GPDI(slot) prvVSIUL[slot]->GPDI123
#define PTD_PIN28_GPDO(slot) prvVSIUL[slot]->GPDO124
#define PTD_PIN28_GPDI(slot) prvVSIUL[slot]->GPDI124
#define PTD_PIN29_GPDO(slot) prvVSIUL[slot]->GPDO125
#define PTD_PIN29_GPDI(slot) prvVSIUL[slot]->GPDI125
#define PTD_PIN30_GPDO(slot) prvVSIUL[slot]->GPDO126
#define PTD_PIN30_GPDI(slot) prvVSIUL[slot]->GPDI126
#define PTD_PIN31_GPDO(slot) prvVSIUL[slot]->GPDO127
#define PTD_PIN31_GPDI(slot) prvVSIUL[slot]->GPDI127
#define PTE_PIN0_GPDO(slot)  prvVSIUL[slot]->GPDO128
#define PTE_PIN0_GPDI(slot)  prvVSIUL[slot]->GPDI128
#define PTE_PIN1_GPDO(slot)  prvVSIUL[slot]->GPDO129
#define PTE_PIN1_GPDI(slot)  prvVSIUL[slot]->GPDI129
#define PTE_PIN2_GPDO(slot)  prvVSIUL[slot]->GPDO130
#define PTE_PIN2_GPDI(slot)  prvVSIUL[slot]->GPDI130
#define PTE_PIN3_GPDO(slot)  prvVSIUL[slot]->GPDO131
#define PTE_PIN3_GPDI(slot)  prvVSIUL[slot]->GPDI131
#define PTE_PIN4_GPDO(slot)  prvVSIUL[slot]->GPDO132
#define PTE_PIN4_GPDI(slot)  prvVSIUL[slot]->GPDI132
#define PTE_PIN5_GPDO(slot)  prvVSIUL[slot]->GPDO133
#define PTE_PIN5_GPDI(slot)  prvVSIUL[slot]->GPDI133
#define PTE_PIN6_GPDO(slot)  prvVSIUL[slot]->GPDO134
#define PTE_PIN6_GPDI(slot)  prvVSIUL[slot]->GPDI134
#define PTE_PIN7_GPDO(slot)  prvVSIUL[slot]->GPDO135
#define PTE_PIN7_GPDI(slot)  prvVSIUL[slot]->GPDI135
#define PTE_PIN8_GPDO(slot)  prvVSIUL[slot]->GPDO136
#define PTE_PIN8_GPDI(slot)  prvVSIUL[slot]->GPDI136
#define PTE_PIN9_GPDO(slot)  prvVSIUL[slot]->GPDO137
#define PTE_PIN9_GPDI(slot)  prvVSIUL[slot]->GPDI137
#define PTE_PIN10_GPDO(slot) prvVSIUL[slot]->GPDO138
#define PTE_PIN10_GPDI(slot) prvVSIUL[slot]->GPDI138
#define PTE_PIN11_GPDO(slot) prvVSIUL[slot]->GPDO139
#define PTE_PIN11_GPDI(slot) prvVSIUL[slot]->GPDI139
#define PTE_PIN12_GPDO(slot) prvVSIUL[slot]->GPDO140
#define PTE_PIN12_GPDI(slot) prvVSIUL[slot]->GPDI140
#define PTE_PIN13_GPDO(slot) prvVSIUL[slot]->GPDO141
#define PTE_PIN13_GPDI(slot) prvVSIUL[slot]->GPDI141
#define PTE_PIN14_GPDO(slot) prvVSIUL[slot]->GPDO142
#define PTE_PIN14_GPDI(slot) prvVSIUL[slot]->GPDI142
#define PTE_PIN15_GPDO(slot) prvVSIUL[slot]->GPDO143
#define PTE_PIN15_GPDI(slot) prvVSIUL[slot]->GPDI143
#define PTE_PIN16_GPDO(slot) prvVSIUL[slot]->GPDO144
#define PTE_PIN16_GPDI(slot) prvVSIUL[slot]->GPDI144
#define PTE_PIN17_GPDO(slot) prvVSIUL[slot]->GPDO145
#define PTE_PIN17_GPDI(slot) prvVSIUL[slot]->GPDI145
#define PTE_PIN18_GPDO(slot) prvVSIUL[slot]->GPDO146
#define PTE_PIN18_GPDI(slot) prvVSIUL[slot]->GPDI146
#define PTE_PIN19_GPDO(slot) prvVSIUL[slot]->GPDO147
#define PTE_PIN19_GPDI(slot) prvVSIUL[slot]->GPDI147
#define PTE_PIN20_GPDO(slot) prvVSIUL[slot]->GPDO148
#define PTE_PIN20_GPDI(slot) prvVSIUL[slot]->GPDI148
#define PTE_PIN21_GPDO(slot) prvVSIUL[slot]->GPDO149
#define PTE_PIN21_GPDI(slot) prvVSIUL[slot]->GPDI149
#define PTE_PIN22_GPDO(slot) prvVSIUL[slot]->GPDO150
#define PTE_PIN22_GPDI(slot) prvVSIUL[slot]->GPDI150
#define PTE_PIN23_GPDO(slot) prvVSIUL[slot]->GPDO151
#define PTE_PIN23_GPDI(slot) prvVSIUL[slot]->GPDI151
#define PTE_PIN24_GPDO(slot) prvVSIUL[slot]->GPDO152
#define PTE_PIN24_GPDI(slot) prvVSIUL[slot]->GPDI152
#define PTE_PIN25_GPDO(slot) prvVSIUL[slot]->GPDO153
#define PTE_PIN25_GPDI(slot) prvVSIUL[slot]->GPDI153
#define PTE_PIN26_GPDO(slot) prvVSIUL[slot]->GPDO154
#define PTE_PIN26_GPDI(slot) prvVSIUL[slot]->GPDI154
#define PTE_PIN27_GPDO(slot) prvVSIUL[slot]->GPDO155
#define PTE_PIN27_GPDI(slot) prvVSIUL[slot]->GPDI155
#define PTE_PIN28_GPDO(slot) prvVSIUL[slot]->GPDO156
#define PTE_PIN28_GPDI(slot) prvVSIUL[slot]->GPDI156
#define PTE_PIN29_GPDO(slot) prvVSIUL[slot]->GPDO157
#define PTE_PIN29_GPDI(slot) prvVSIUL[slot]->GPDI157
#define PTE_PIN30_GPDO(slot) prvVSIUL[slot]->GPDO158
#define PTE_PIN30_GPDI(slot) prvVSIUL[slot]->GPDI158
#define PTE_PIN31_GPDO(slot) prvVSIUL[slot]->GPDO159
#define PTE_PIN31_GPDI(slot) prvVSIUL[slot]->GPDI159
#define PTF_PIN0_GPDO(slot)  prvVSIUL[slot]->GPDO160
#define PTF_PIN0_GPDI(slot)  prvVSIUL[slot]->GPDI160
#define PTF_PIN1_GPDO(slot)  prvVSIUL[slot]->GPDO161
#define PTF_PIN1_GPDI(slot)  prvVSIUL[slot]->GPDI161
#define PTF_PIN2_GPDO(slot)  prvVSIUL[slot]->GPDO162
#define PTF_PIN2_GPDI(slot)  prvVSIUL[slot]->GPDI162
#define PTF_PIN3_GPDO(slot)  prvVSIUL[slot]->GPDO163
#define PTF_PIN3_GPDI(slot)  prvVSIUL[slot]->GPDI163
#define PTF_PIN4_GPDO(slot)  prvVSIUL[slot]->GPDO164
#define PTF_PIN4_GPDI(slot)  prvVSIUL[slot]->GPDI164
#define PTF_PIN5_GPDO(slot)  prvVSIUL[slot]->GPDO165
#define PTF_PIN5_GPDI(slot)  prvVSIUL[slot]->GPDI165
#define PTF_PIN6_GPDO(slot)  prvVSIUL[slot]->GPDO166
#define PTF_PIN6_GPDI(slot)  prvVSIUL[slot]->GPDI166
#define PTF_PIN7_GPDO(slot)  prvVSIUL[slot]->GPDO167
#define PTF_PIN7_GPDI(slot)  prvVSIUL[slot]->GPDI167
#define PTF_PIN8_GPDO(slot)  prvVSIUL[slot]->GPDO168
#define PTF_PIN8_GPDI(slot)  prvVSIUL[slot]->GPDI168
#define PTF_PIN9_GPDO(slot)  prvVSIUL[slot]->GPDO169
#define PTF_PIN9_GPDI(slot)  prvVSIUL[slot]->GPDI169
#define PTF_PIN10_GPDO(slot) prvVSIUL[slot]->GPDO170
#define PTF_PIN10_GPDI(slot) prvVSIUL[slot]->GPDI170
#define PTF_PIN11_GPDO(slot) prvVSIUL[slot]->GPDO171
#define PTF_PIN11_GPDI(slot) prvVSIUL[slot]->GPDI171
#define PTF_PIN12_GPDO(slot) prvVSIUL[slot]->GPDO172
#define PTF_PIN12_GPDI(slot) prvVSIUL[slot]->GPDI172
#define PTF_PIN13_GPDO(slot) prvVSIUL[slot]->GPDO173
#define PTF_PIN13_GPDI(slot) prvVSIUL[slot]->GPDI173
#define PTF_PIN14_GPDO(slot) prvVSIUL[slot]->GPDO174
#define PTF_PIN14_GPDI(slot) prvVSIUL[slot]->GPDI174
#define PTF_PIN15_GPDO(slot) prvVSIUL[slot]->GPDO175
#define PTF_PIN15_GPDI(slot) prvVSIUL[slot]->GPDI175
#define PTF_PIN16_GPDO(slot) prvVSIUL[slot]->GPDO176
#define PTF_PIN16_GPDI(slot) prvVSIUL[slot]->GPDI176
#define PTF_PIN17_GPDO(slot) prvVSIUL[slot]->GPDO177
#define PTF_PIN17_GPDI(slot) prvVSIUL[slot]->GPDI177
#define PTF_PIN18_GPDO(slot) prvVSIUL[slot]->GPDO178
#define PTF_PIN18_GPDI(slot) prvVSIUL[slot]->GPDI178
#define PTF_PIN19_GPDO(slot) prvVSIUL[slot]->GPDO179
#define PTF_PIN19_GPDI(slot) prvVSIUL[slot]->GPDI179
#define PTF_PIN20_GPDO(slot) prvVSIUL[slot]->GPDO180
#define PTF_PIN20_GPDI(slot) prvVSIUL[slot]->GPDI180
#define PTF_PIN21_GPDO(slot) prvVSIUL[slot]->GPDO181
#define PTF_PIN21_GPDI(slot) prvVSIUL[slot]->GPDI181
#define PTF_PIN22_GPDO(slot) prvVSIUL[slot]->GPDO182
#define PTF_PIN22_GPDI(slot) prvVSIUL[slot]->GPDI182
#define PTF_PIN23_GPDO(slot) prvVSIUL[slot]->GPDO183
#define PTF_PIN23_GPDI(slot) prvVSIUL[slot]->GPDI183
#define PTF_PIN24_GPDO(slot) prvVSIUL[slot]->GPDO184
#define PTF_PIN24_GPDI(slot) prvVSIUL[slot]->GPDI184
#define PTF_PIN25_GPDO(slot) prvVSIUL[slot]->GPDO185
#define PTF_PIN25_GPDI(slot) prvVSIUL[slot]->GPDI185
#define PTF_PIN26_GPDO(slot) prvVSIUL[slot]->GPDO186
#define PTF_PIN26_GPDI(slot) prvVSIUL[slot]->GPDI186
#define PTF_PIN27_GPDO(slot) prvVSIUL[slot]->GPDO187
#define PTF_PIN27_GPDI(slot) prvVSIUL[slot]->GPDI187
#define PTF_PIN28_GPDO(slot) prvVSIUL[slot]->GPDO188
#define PTF_PIN28_GPDI(slot) prvVSIUL[slot]->GPDI188
#define PTF_PIN29_GPDO(slot) prvVSIUL[slot]->GPDO189
#define PTF_PIN29_GPDI(slot) prvVSIUL[slot]->GPDI189
#define PTF_PIN30_GPDO(slot) prvVSIUL[slot]->GPDO190
#define PTF_PIN30_GPDI(slot) prvVSIUL[slot]->GPDI190
#define PTF_PIN31_GPDO(slot) prvVSIUL[slot]->GPDO191
#define PTF_PIN31_GPDI(slot) prvVSIUL[slot]->GPDI191
#define PTG_PIN0_GPDO(slot)  prvVSIUL[slot]->GPDO192
#define PTG_PIN0_GPDI(slot)  prvVSIUL[slot]->GPDI192
#define PTG_PIN1_GPDO(slot)  prvVSIUL[slot]->GPDO193
#define PTG_PIN1_GPDI(slot)  prvVSIUL[slot]->GPDI193
#define PTG_PIN2_GPDO(slot)  prvVSIUL[slot]->GPDO194
#define PTG_PIN2_GPDI(slot)  prvVSIUL[slot]->GPDI194
#define PTG_PIN3_GPDO(slot)  prvVSIUL[slot]->GPDO195
#define PTG_PIN3_GPDI(slot)  prvVSIUL[slot]->GPDI195
#define PTG_PIN4_GPDO(slot)  prvVSIUL[slot]->GPDO196
#define PTG_PIN4_GPDI(slot)  prvVSIUL[slot]->GPDI196
#define PTG_PIN5_GPDO(slot)  prvVSIUL[slot]->GPDO197
#define PTG_PIN5_GPDI(slot)  prvVSIUL[slot]->GPDI197
#define PTG_PIN6_GPDO(slot)  prvVSIUL[slot]->GPDO198
#define PTG_PIN6_GPDI(slot)  prvVSIUL[slot]->GPDI198
#define PTG_PIN7_GPDO(slot)  prvVSIUL[slot]->GPDO199
#define PTG_PIN7_GPDI(slot)  prvVSIUL[slot]->GPDI199
#define PTG_PIN8_GPDO(slot)  prvVSIUL[slot]->GPDO200
#define PTG_PIN8_GPDI(slot)  prvVSIUL[slot]->GPDI200
#define PTG_PIN9_GPDO(slot)  prvVSIUL[slot]->GPDO201
#define PTG_PIN9_GPDI(slot)  prvVSIUL[slot]->GPDI201
#define PTG_PIN10_GPDO(slot) prvVSIUL[slot]->GPDO202
#define PTG_PIN10_GPDI(slot) prvVSIUL[slot]->GPDI202
#define PTG_PIN11_GPDO(slot) prvVSIUL[slot]->GPDO203
#define PTG_PIN11_GPDI(slot) prvVSIUL[slot]->GPDI203
#define PTG_PIN12_GPDO(slot) prvVSIUL[slot]->GPDO204
#define PTG_PIN12_GPDI(slot) prvVSIUL[slot]->GPDI204
#define PTG_PIN13_GPDO(slot) prvVSIUL[slot]->GPDO205
#define PTG_PIN13_GPDI(slot) prvVSIUL[slot]->GPDI205
#define PTG_PIN14_GPDO(slot) prvVSIUL[slot]->GPDO206
#define PTG_PIN14_GPDI(slot) prvVSIUL[slot]->GPDI206
#define PTG_PIN15_GPDO(slot) prvVSIUL[slot]->GPDO207
#define PTG_PIN15_GPDI(slot) prvVSIUL[slot]->GPDI207
#define PTG_PIN16_GPDO(slot) prvVSIUL[slot]->GPDO208
#define PTG_PIN16_GPDI(slot) prvVSIUL[slot]->GPDI208
#define PTG_PIN17_GPDO(slot) prvVSIUL[slot]->GPDO209
#define PTG_PIN17_GPDI(slot) prvVSIUL[slot]->GPDI209
#define PTG_PIN18_GPDO(slot) prvVSIUL[slot]->GPDO210
#define PTG_PIN18_GPDI(slot) prvVSIUL[slot]->GPDI210
#define PTG_PIN19_GPDO(slot) prvVSIUL[slot]->GPDO211
#define PTG_PIN19_GPDI(slot) prvVSIUL[slot]->GPDI211
#define PTG_PIN20_GPDO(slot) prvVSIUL[slot]->GPDO212
#define PTG_PIN20_GPDI(slot) prvVSIUL[slot]->GPDI212
#define PTG_PIN21_GPDO(slot) prvVSIUL[slot]->GPDO213
#define PTG_PIN21_GPDI(slot) prvVSIUL[slot]->GPDI213
#define PTG_PIN22_GPDO(slot) prvVSIUL[slot]->GPDO214
#define PTG_PIN22_GPDI(slot) prvVSIUL[slot]->GPDI214
#define PTG_PIN23_GPDO(slot) prvVSIUL[slot]->GPDO215
#define PTG_PIN23_GPDI(slot) prvVSIUL[slot]->GPDI215
#define PTG_PIN24_GPDO(slot) prvVSIUL[slot]->GPDO216
#define PTG_PIN24_GPDI(slot) prvVSIUL[slot]->GPDI216
#define PTG_PIN25_GPDO(slot) prvVSIUL[slot]->GPDO217
#define PTG_PIN25_GPDI(slot) prvVSIUL[slot]->GPDI217
#define PTG_PIN26_GPDO(slot) prvVSIUL[slot]->GPDO218
#define PTG_PIN26_GPDI(slot) prvVSIUL[slot]->GPDI218
#define PTG_PIN27_GPDO(slot) prvVSIUL[slot]->GPDO219
#define PTG_PIN27_GPDI(slot) prvVSIUL[slot]->GPDI219
#define PTG_PIN28_GPDO(slot) prvVSIUL[slot]->GPDO220
#define PTG_PIN28_GPDI(slot) prvVSIUL[slot]->GPDI220
#define PTG_PIN29_GPDO(slot) prvVSIUL[slot]->GPDO221
#define PTG_PIN29_GPDI(slot) prvVSIUL[slot]->GPDI221
#define PTG_PIN30_GPDO(slot) prvVSIUL[slot]->GPDO222
#define PTG_PIN30_GPDI(slot) prvVSIUL[slot]->GPDI222
#define PTG_PIN31_GPDO(slot) prvVSIUL[slot]->GPDO223
#define PTG_PIN31_GPDI(slot) prvVSIUL[slot]->GPDI223
#define PTH_PIN0_GPDO(slot)  prvVSIUL[slot]->GPDO224
#define PTH_PIN0_GPDI(slot)  prvVSIUL[slot]->GPDI224
#define PTH_PIN1_GPDO(slot)  prvVSIUL[slot]->GPDO225
#define PTH_PIN1_GPDI(slot)  prvVSIUL[slot]->GPDI225
#define PTH_PIN2_GPDO(slot)  prvVSIUL[slot]->GPDO226
#define PTH_PIN2_GPDI(slot)  prvVSIUL[slot]->GPDI226
#define PTH_PIN3_GPDO(slot)  prvVSIUL[slot]->GPDO227
#define PTH_PIN3_GPDI(slot)  prvVSIUL[slot]->GPDI227
#define PTH_PIN4_GPDO(slot)  prvVSIUL[slot]->GPDO228
#define PTH_PIN4_GPDI(slot)  prvVSIUL[slot]->GPDI228
#define PTH_PIN5_GPDO(slot)  prvVSIUL[slot]->GPDO229
#define PTH_PIN5_GPDI(slot)  prvVSIUL[slot]->GPDI229
#define PTH_PIN6_GPDO(slot)  prvVSIUL[slot]->GPDO230
#define PTH_PIN6_GPDI(slot)  prvVSIUL[slot]->GPDI230
#define PTH_PIN7_GPDO(slot)  prvVSIUL[slot]->GPDO231
#define PTH_PIN7_GPDI(slot)  prvVSIUL[slot]->GPDI231
#define PTH_PIN8_GPDO(slot)  prvVSIUL[slot]->GPDO232
#define PTH_PIN8_GPDI(slot)  prvVSIUL[slot]->GPDI232
#define PTH_PIN9_GPDO(slot)  prvVSIUL[slot]->GPDO233
#define PTH_PIN9_GPDI(slot)  prvVSIUL[slot]->GPDI233
#define PTH_PIN10_GPDO(slot) prvVSIUL[slot]->GPDO234
#define PTH_PIN10_GPDI(slot) prvVSIUL[slot]->GPDI234
#define PTH_PIN11_GPDO(slot) prvVSIUL[slot]->GPDO235
#define PTH_PIN11_GPDI(slot) prvVSIUL[slot]->GPDI235
#define PTH_PIN12_GPDO(slot) prvVSIUL[slot]->GPDO236
#define PTH_PIN12_GPDI(slot) prvVSIUL[slot]->GPDI236
#define PTH_PIN13_GPDO(slot) prvVSIUL[slot]->GPDO237
#define PTH_PIN13_GPDI(slot) prvVSIUL[slot]->GPDI237
#define PTH_PIN14_GPDO(slot) prvVSIUL[slot]->GPDO238
#define PTH_PIN14_GPDI(slot) prvVSIUL[slot]->GPDI238
#define PTH_PIN15_GPDO(slot) prvVSIUL[slot]->GPDO239
#define PTH_PIN15_GPDI(slot) prvVSIUL[slot]->GPDI239
#define PTH_PIN16_GPDO(slot) prvVSIUL[slot]->GPDO240
#define PTH_PIN16_GPDI(slot) prvVSIUL[slot]->GPDI240
#define PTH_PIN17_GPDO(slot) prvVSIUL[slot]->GPDO241
#define PTH_PIN17_GPDI(slot) prvVSIUL[slot]->GPDI241
#define PTH_PIN18_GPDO(slot) prvVSIUL[slot]->GPDO242
#define PTH_PIN18_GPDI(slot) prvVSIUL[slot]->GPDI242
#define PTH_PIN19_GPDO(slot) prvVSIUL[slot]->GPDO243
#define PTH_PIN19_GPDI(slot) prvVSIUL[slot]->GPDI243
#define PTH_PIN20_GPDO(slot) prvVSIUL[slot]->GPDO244
#define PTH_PIN20_GPDI(slot) prvVSIUL[slot]->GPDI244
#define PIN_GRP0_PGDO(slot)  prvVSIUL[slot]->PGPDO0
#define PIN_GRP1_PGDO(slot)  prvVSIUL[slot]->PGPDO1
#define PIN_GRP2_PGDO(slot)  prvVSIUL[slot]->PGPDO2
#define PIN_GRP3_PGDO(slot)  prvVSIUL[slot]->PGPDO3
#define PIN_GRP4_PGDO(slot)  prvVSIUL[slot]->PGPDO4
#define PIN_GRP5_PGDO(slot)  prvVSIUL[slot]->PGPDO5
#define PIN_GRP6_PGDO(slot)  prvVSIUL[slot]->PGPDO6
#define PIN_GRP7_PGDO(slot)  prvVSIUL[slot]->PGPDO7
#define PIN_GRP8_PGDO(slot)  prvVSIUL[slot]->PGPDO8
#define PIN_GRP9_PGDO(slot)  prvVSIUL[slot]->PGPDO9
#define PIN_GRP10_PGDO(slot) prvVSIUL[slot]->PGPDO10
#define PIN_GRP11_PGDO(slot) prvVSIUL[slot]->PGPDO11
#define PIN_GRP12_PGDO(slot) prvVSIUL[slot]->PGPDO12
#define PIN_GRP13_PGDO(slot) prvVSIUL[slot]->PGPDO13
#define PIN_GRP14_PGDO(slot) prvVSIUL[slot]->PGPDO14
#define PIN_GRP15_PGDO(slot) prvVSIUL[slot]->PGPDO15
#define PIN_GRP0_MPGDO(slot) prvVSIUL[slot]->MPGPDO[0]
#define PIN_GRP1_MPGDO(slot) prvVSIUL[slot]->MPGPDO[1]
#define PIN_GRP2_MPGDO(slot) prvVSIUL[slot]->MPGPDO[2]
#define PIN_GRP3_MPGDO(slot) prvVSIUL[slot]->MPGPDO[3]
#define PIN_GRP4_MPGDO(slot) prvVSIUL[slot]->MPGPDO[4]
#define PIN_GRP5_MPGDO(slot) prvVSIUL[slot]->MPGPDO[5]
#define PIN_GRP6_MPGDO(slot) prvVSIUL[slot]->MPGPDO[6]
#define PIN_GRP7_MPGDO(slot) prvVSIUL[slot]->MPGPDO[7]
#define PIN_GRP8_MPGDO(slot) prvVSIUL[slot]->MPGPDO[8]
#define PIN_GRP9_MPGDO(slot) prvVSIUL[slot]->MPGPDO[9]
#define PIN_GRP10_MPGDO(slot) prvVSIUL[slot]->MPGPDO[10]
#define PIN_GRP11_MPGDO(slot) prvVSIUL[slot]->MPGPDO[11]
#define PIN_GRP12_MPGDO(slot) prvVSIUL[slot]->MPGPDO[12]
#define PIN_GRP13_MPGDO(slot) prvVSIUL[slot]->MPGPDO[13]
#define PIN_GRP14_MPGDO(slot) prvVSIUL[slot]->MPGPDO[14]
#define PIN_GRP15_MPGDO(slot) prvVSIUL[slot]->MPGPDO[15]
#define PIN_GRP0_PGDI(slot)  prvVSIUL[slot]->PGPDI0
#define PIN_GRP1_PGDI(slot)  prvVSIUL[slot]->PGPDI1
#define PIN_GRP2_PGDI(slot)  prvVSIUL[slot]->PGPDI2
#define PIN_GRP3_PGDI(slot)  prvVSIUL[slot]->PGPDI3
#define PIN_GRP4_PGDI(slot)  prvVSIUL[slot]->PGPDI4
#define PIN_GRP5_PGDI(slot)  prvVSIUL[slot]->PGPDI5
#define PIN_GRP6_PGDI(slot)  prvVSIUL[slot]->PGPDI6
#define PIN_GRP7_PGDI(slot)  prvVSIUL[slot]->PGPDI7
#define PIN_GRP8_PGDI(slot)  prvVSIUL[slot]->PGPDI8
#define PIN_GRP9_PGDI(slot)  prvVSIUL[slot]->PGPDI9
#define PIN_GRP10_PGDI(slot) prvVSIUL[slot]->PGPDI10
#define PIN_GRP11_PGDI(slot) prvVSIUL[slot]->PGPDI11
#define PIN_GRP12_PGDI(slot) prvVSIUL[slot]->PGPDI12
#define PIN_GRP13_PGDI(slot) prvVSIUL[slot]->PGPDI13
#define PIN_GRP14_PGDI(slot) prvVSIUL[slot]->PGPDI14
#define PIN_GRP15_PGDI(slot) prvVSIUL[slot]->PGPDI15
#define PTA_PIN0_MSCR(slot)  prvVSIUL[slot]->MSCR[0]
#define PTA_PIN1_MSCR(slot)  prvVSIUL[slot]->MSCR[1]
#define PTA_PIN2_MSCR(slot)  prvVSIUL[slot]->MSCR[2]
#define PTA_PIN3_MSCR(slot)  prvVSIUL[slot]->MSCR[3]
#define PTA_PIN4_MSCR(slot)  prvVSIUL[slot]->MSCR[4]
#define PTA_PIN5_MSCR(slot)  prvVSIUL[slot]->MSCR[5]
#define PTA_PIN6_MSCR(slot)  prvVSIUL[slot]->MSCR[6]
#define PTA_PIN7_MSCR(slot)  prvVSIUL[slot]->MSCR[7]
#define PTA_PIN8_MSCR(slot)  prvVSIUL[slot]->MSCR[8]
#define PTA_PIN9_MSCR(slot)  prvVSIUL[slot]->MSCR[9]
#define PTA_PIN10_MSCR(slot) prvVSIUL[slot]->MSCR[10]
#define PTA_PIN11_MSCR(slot) prvVSIUL[slot]->MSCR[11]
#define PTA_PIN12_MSCR(slot) prvVSIUL[slot]->MSCR[12]
#define PTA_PIN13_MSCR(slot) prvVSIUL[slot]->MSCR[13]
#define PTA_PIN14_MSCR(slot) prvVSIUL[slot]->MSCR[14]
#define PTA_PIN15_MSCR(slot) prvVSIUL[slot]->MSCR[15]
#define PTA_PIN16_MSCR(slot) prvVSIUL[slot]->MSCR[16]
#define PTA_PIN17_MSCR(slot) prvVSIUL[slot]->MSCR[17]
#define PTA_PIN18_MSCR(slot) prvVSIUL[slot]->MSCR[18]
#define PTA_PIN19_MSCR(slot) prvVSIUL[slot]->MSCR[19]
#define PTA_PIN20_MSCR(slot) prvVSIUL[slot]->MSCR[20]
#define PTA_PIN21_MSCR(slot) prvVSIUL[slot]->MSCR[21]
#define PTA_PIN22_MSCR(slot) prvVSIUL[slot]->MSCR[22]
#define PTA_PIN23_MSCR(slot) prvVSIUL[slot]->MSCR[23]
#define PTA_PIN26_MSCR(slot) prvVSIUL[slot]->MSCR[26]
#define PTA_PIN27_MSCR(slot) prvVSIUL[slot]->MSCR[27]
#define PTA_PIN28_MSCR(slot) prvVSIUL[slot]->MSCR[28]
#define PTA_PIN29_MSCR(slot) prvVSIUL[slot]->MSCR[29]
#define PTA_PIN30_MSCR(slot) prvVSIUL[slot]->MSCR[30]
#define PTA_PIN31_MSCR(slot) prvVSIUL[slot]->MSCR[31]
#define PTB_PIN0_MSCR(slot)  prvVSIUL[slot]->MSCR[32]
#define PTB_PIN1_MSCR(slot)  prvVSIUL[slot]->MSCR[33]
#define PTB_PIN2_MSCR(slot)  prvVSIUL[slot]->MSCR[34]
#define PTB_PIN3_MSCR(slot)  prvVSIUL[slot]->MSCR[35]
#define PTB_PIN4_MSCR(slot)  prvVSIUL[slot]->MSCR[36]
#define PTB_PIN5_MSCR(slot)  prvVSIUL[slot]->MSCR[37]
#define PTB_PIN8_MSCR(slot)  prvVSIUL[slot]->MSCR[40]
#define PTB_PIN9_MSCR(slot)  prvVSIUL[slot]->MSCR[41]
#define PTB_PIN10_MSCR(slot) prvVSIUL[slot]->MSCR[42]
#define PTB_PIN11_MSCR(slot) prvVSIUL[slot]->MSCR[43]
#define PTB_PIN12_MSCR(slot) prvVSIUL[slot]->MSCR[44]
#define PTB_PIN13_MSCR(slot) prvVSIUL[slot]->MSCR[45]
#define PTB_PIN14_MSCR(slot) prvVSIUL[slot]->MSCR[46]
#define PTB_PIN15_MSCR(slot) prvVSIUL[slot]->MSCR[47]
#define PTB_PIN16_MSCR(slot) prvVSIUL[slot]->MSCR[48]
#define PTB_PIN17_MSCR(slot) prvVSIUL[slot]->MSCR[49]
#define PTB_PIN18_MSCR(slot) prvVSIUL[slot]->MSCR[50]
#define PTB_PIN19_MSCR(slot) prvVSIUL[slot]->MSCR[51]
#define PTB_PIN20_MSCR(slot) prvVSIUL[slot]->MSCR[52]
#define PTB_PIN21_MSCR(slot) prvVSIUL[slot]->MSCR[53]
#define PTB_PIN22_MSCR(slot) prvVSIUL[slot]->MSCR[54]
#define PTB_PIN23_MSCR(slot) prvVSIUL[slot]->MSCR[55]
#define PTB_PIN24_MSCR(slot) prvVSIUL[slot]->MSCR[56]
#define PTB_PIN25_MSCR(slot) prvVSIUL[slot]->MSCR[57]
#define PTB_PIN26_MSCR(slot) prvVSIUL[slot]->MSCR[58]
#define PTB_PIN27_MSCR(slot) prvVSIUL[slot]->MSCR[59]
#define PTB_PIN28_MSCR(slot) prvVSIUL[slot]->MSCR[60]
#define PTB_PIN29_MSCR(slot) prvVSIUL[slot]->MSCR[61]
#define PTB_PIN30_MSCR(slot) prvVSIUL[slot]->MSCR[62]
#define PTB_PIN31_MSCR(slot) prvVSIUL[slot]->MSCR[63]
#define PTC_PIN0_MSCR(slot)  prvVSIUL[slot]->MSCR[64]
#define PTC_PIN1_MSCR(slot)  prvVSIUL[slot]->MSCR[65]
#define PTC_PIN2_MSCR(slot)  prvVSIUL[slot]->MSCR[66]
#define PTC_PIN3_MSCR(slot)  prvVSIUL[slot]->MSCR[67]
#define PTC_PIN4_MSCR(slot)  prvVSIUL[slot]->MSCR[68]
#define PTC_PIN5_MSCR(slot)  prvVSIUL[slot]->MSCR[69]
#define PTC_PIN6_MSCR(slot)  prvVSIUL[slot]->MSCR[70]
#define PTC_PIN7_MSCR(slot)  prvVSIUL[slot]->MSCR[71]
#define PTC_PIN8_MSCR(slot)  prvVSIUL[slot]->MSCR[72]
#define PTC_PIN9_MSCR(slot)  prvVSIUL[slot]->MSCR[73]
#define PTC_PIN10_MSCR(slot) prvVSIUL[slot]->MSCR[74]
#define PTC_PIN11_MSCR(slot) prvVSIUL[slot]->MSCR[75]
#define PTC_PIN12_MSCR(slot) prvVSIUL[slot]->MSCR[76]
#define PTC_PIN13_MSCR(slot) prvVSIUL[slot]->MSCR[77]
#define PTC_PIN14_MSCR(slot) prvVSIUL[slot]->MSCR[78]
#define PTC_PIN15_MSCR(slot) prvVSIUL[slot]->MSCR[79]
#define PTC_PIN16_MSCR(slot) prvVSIUL[slot]->MSCR[80]
#define PTC_PIN17_MSCR(slot) prvVSIUL[slot]->MSCR[81]
#define PTC_PIN18_MSCR(slot) prvVSIUL[slot]->MSCR[82]
#define PTC_PIN19_MSCR(slot) prvVSIUL[slot]->MSCR[83]
#define PTC_PIN20_MSCR(slot) prvVSIUL[slot]->MSCR[84]
#define PTC_PIN21_MSCR(slot) prvVSIUL[slot]->MSCR[85]
#define PTC_PIN22_MSCR(slot) prvVSIUL[slot]->MSCR[86]
#define PTC_PIN23_MSCR(slot) prvVSIUL[slot]->MSCR[87]
#define PTC_PIN24_MSCR(slot) prvVSIUL[slot]->MSCR[88]
#define PTC_PIN25_MSCR(slot) prvVSIUL[slot]->MSCR[89]
#define PTC_PIN26_MSCR(slot) prvVSIUL[slot]->MSCR[90]
#define PTC_PIN27_MSCR(slot) prvVSIUL[slot]->MSCR[91]
#define PTC_PIN28_MSCR(slot) prvVSIUL[slot]->MSCR[92]
#define PTC_PIN29_MSCR(slot) prvVSIUL[slot]->MSCR[93]
#define PTC_PIN30_MSCR(slot) prvVSIUL[slot]->MSCR[94]
#define PTC_PIN31_MSCR(slot) prvVSIUL[slot]->MSCR[95]
#define PTD_PIN0_MSCR(slot)  prvVSIUL[slot]->MSCR[96]
#define PTD_PIN1_MSCR(slot)  prvVSIUL[slot]->MSCR[97]
#define PTD_PIN2_MSCR(slot)  prvVSIUL[slot]->MSCR[98]
#define PTD_PIN3_MSCR(slot)  prvVSIUL[slot]->MSCR[99]
#define PTD_PIN4_MSCR(slot)  prvVSIUL[slot]->MSCR[100]
#define PTD_PIN5_MSCR(slot)  prvVSIUL[slot]->MSCR[101]
#define PTD_PIN6_MSCR(slot)  prvVSIUL[slot]->MSCR[102]
#define PTD_PIN7_MSCR(slot)  prvVSIUL[slot]->MSCR[103]
#define PTD_PIN8_MSCR(slot)  prvVSIUL[slot]->MSCR[104]
#define PTD_PIN9_MSCR(slot)  prvVSIUL[slot]->MSCR[105]
#define PTD_PIN10_MSCR(slot) prvVSIUL[slot]->MSCR[106]
#define PTD_PIN11_MSCR(slot) prvVSIUL[slot]->MSCR[107]
#define PTD_PIN12_MSCR(slot) prvVSIUL[slot]->MSCR[108]
#define PTD_PIN13_MSCR(slot) prvVSIUL[slot]->MSCR[109]
#define PTD_PIN14_MSCR(slot) prvVSIUL[slot]->MSCR[110]
#define PTD_PIN15_MSCR(slot) prvVSIUL[slot]->MSCR[111]
#define PTD_PIN16_MSCR(slot) prvVSIUL[slot]->MSCR[112]
#define PTD_PIN17_MSCR(slot) prvVSIUL[slot]->MSCR[113]
#define PTD_PIN18_MSCR(slot) prvVSIUL[slot]->MSCR[114]
#define PTD_PIN19_MSCR(slot) prvVSIUL[slot]->MSCR[115]
#define PTD_PIN20_MSCR(slot) prvVSIUL[slot]->MSCR[116]
#define PTD_PIN21_MSCR(slot) prvVSIUL[slot]->MSCR[117]
#define PTD_PIN22_MSCR(slot) prvVSIUL[slot]->MSCR[118]
#define PTD_PIN23_MSCR(slot) prvVSIUL[slot]->MSCR[119]
#define PTD_PIN24_MSCR(slot) prvVSIUL[slot]->MSCR[120]
#define PTD_PIN25_MSCR(slot) prvVSIUL[slot]->MSCR[121]
#define PTD_PIN26_MSCR(slot) prvVSIUL[slot]->MSCR[122]
#define PTD_PIN27_MSCR(slot) prvVSIUL[slot]->MSCR[123]
#define PTD_PIN28_MSCR(slot) prvVSIUL[slot]->MSCR[124]
#define PTD_PIN29_MSCR(slot) prvVSIUL[slot]->MSCR[125]
#define PTD_PIN30_MSCR(slot) prvVSIUL[slot]->MSCR[126]
#define PTD_PIN31_MSCR(slot) prvVSIUL[slot]->MSCR[127]
#define PTE_PIN0_MSCR(slot)  prvVSIUL[slot]->MSCR[128]
#define PTE_PIN1_MSCR(slot)  prvVSIUL[slot]->MSCR[129]
#define PTE_PIN2_MSCR(slot)  prvVSIUL[slot]->MSCR[130]
#define PTE_PIN3_MSCR(slot)  prvVSIUL[slot]->MSCR[131]
#define PTE_PIN4_MSCR(slot)  prvVSIUL[slot]->MSCR[132]
#define PTE_PIN5_MSCR(slot)  prvVSIUL[slot]->MSCR[133]
#define PTE_PIN6_MSCR(slot)  prvVSIUL[slot]->MSCR[134]
#define PTE_PIN7_MSCR(slot)  prvVSIUL[slot]->MSCR[135]
#define PTE_PIN8_MSCR(slot)  prvVSIUL[slot]->MSCR[136]
#define PTE_PIN9_MSCR(slot)  prvVSIUL[slot]->MSCR[137]
#define PTE_PIN10_MSCR(slot) prvVSIUL[slot]->MSCR[138]
#define PTE_PIN11_MSCR(slot) prvVSIUL[slot]->MSCR[139]
#define PTE_PIN12_MSCR(slot) prvVSIUL[slot]->MSCR[140]
#define PTE_PIN13_MSCR(slot) prvVSIUL[slot]->MSCR[141]
#define PTE_PIN14_MSCR(slot) prvVSIUL[slot]->MSCR[142]
#define PTE_PIN15_MSCR(slot) prvVSIUL[slot]->MSCR[143]
#define PTE_PIN16_MSCR(slot) prvVSIUL[slot]->MSCR[144]
#define PTE_PIN17_MSCR(slot) prvVSIUL[slot]->MSCR[145]
#define PTE_PIN18_MSCR(slot) prvVSIUL[slot]->MSCR[146]
#define PTE_PIN19_MSCR(slot) prvVSIUL[slot]->MSCR[147]
#define PTE_PIN20_MSCR(slot) prvVSIUL[slot]->MSCR[148]
#define PTE_PIN21_MSCR(slot) prvVSIUL[slot]->MSCR[149]
#define PTE_PIN22_MSCR(slot) prvVSIUL[slot]->MSCR[150]
#define PTE_PIN23_MSCR(slot) prvVSIUL[slot]->MSCR[151]
#define PTE_PIN24_MSCR(slot) prvVSIUL[slot]->MSCR[152]
#define PTE_PIN25_MSCR(slot) prvVSIUL[slot]->MSCR[153]
#define PTE_PIN26_MSCR(slot) prvVSIUL[slot]->MSCR[154]
#define PTE_PIN27_MSCR(slot) prvVSIUL[slot]->MSCR[155]
#define PTE_PIN28_MSCR(slot) prvVSIUL[slot]->MSCR[156]
#define PTE_PIN29_MSCR(slot) prvVSIUL[slot]->MSCR[157]
#define PTE_PIN30_MSCR(slot) prvVSIUL[slot]->MSCR[158]
#define PTE_PIN31_MSCR(slot) prvVSIUL[slot]->MSCR[159]
#define PTF_PIN0_MSCR(slot)  prvVSIUL[slot]->MSCR[160]
#define PTF_PIN1_MSCR(slot)  prvVSIUL[slot]->MSCR[161]
#define PTF_PIN2_MSCR(slot)  prvVSIUL[slot]->MSCR[162]
#define PTF_PIN3_MSCR(slot)  prvVSIUL[slot]->MSCR[163]
#define PTF_PIN4_MSCR(slot)  prvVSIUL[slot]->MSCR[164]
#define PTF_PIN5_MSCR(slot)  prvVSIUL[slot]->MSCR[165]
#define PTF_PIN6_MSCR(slot)  prvVSIUL[slot]->MSCR[166]
#define PTF_PIN7_MSCR(slot)  prvVSIUL[slot]->MSCR[167]
#define PTF_PIN8_MSCR(slot)  prvVSIUL[slot]->MSCR[168]
#define PTF_PIN9_MSCR(slot)  prvVSIUL[slot]->MSCR[169]
#define PTF_PIN10_MSCR(slot) prvVSIUL[slot]->MSCR[170]
#define PTF_PIN11_MSCR(slot) prvVSIUL[slot]->MSCR[171]
#define PTF_PIN12_MSCR(slot) prvVSIUL[slot]->MSCR[172]
#define PTF_PIN13_MSCR(slot) prvVSIUL[slot]->MSCR[173]
#define PTF_PIN14_MSCR(slot) prvVSIUL[slot]->MSCR[174]
#define PTF_PIN15_MSCR(slot) prvVSIUL[slot]->MSCR[175]
#define PTF_PIN16_MSCR(slot) prvVSIUL[slot]->MSCR[176]
#define PTF_PIN17_MSCR(slot) prvVSIUL[slot]->MSCR[177]
#define PTF_PIN18_MSCR(slot) prvVSIUL[slot]->MSCR[178]
#define PTF_PIN19_MSCR(slot) prvVSIUL[slot]->MSCR[179]
#define PTF_PIN20_MSCR(slot) prvVSIUL[slot]->MSCR[180]
#define PTF_PIN21_MSCR(slot) prvVSIUL[slot]->MSCR[181]
#define PTF_PIN22_MSCR(slot) prvVSIUL[slot]->MSCR[182]
#define PTF_PIN23_MSCR(slot) prvVSIUL[slot]->MSCR[183]
#define PTF_PIN24_MSCR(slot) prvVSIUL[slot]->MSCR[184]
#define PTF_PIN25_MSCR(slot) prvVSIUL[slot]->MSCR[185]
#define PTF_PIN26_MSCR(slot) prvVSIUL[slot]->MSCR[186]
#define PTF_PIN27_MSCR(slot) prvVSIUL[slot]->MSCR[187]
#define PTF_PIN28_MSCR(slot) prvVSIUL[slot]->MSCR[188]
#define PTF_PIN29_MSCR(slot) prvVSIUL[slot]->MSCR[189]
#define PTF_PIN30_MSCR(slot) prvVSIUL[slot]->MSCR[190]
#define PTF_PIN31_MSCR(slot) prvVSIUL[slot]->MSCR[191]
#define PTG_PIN0_MSCR(slot)  prvVSIUL[slot]->MSCR[192]
#define PTG_PIN1_MSCR(slot)  prvVSIUL[slot]->MSCR[193]
#define PTG_PIN2_MSCR(slot)  prvVSIUL[slot]->MSCR[194]
#define PTG_PIN3_MSCR(slot)  prvVSIUL[slot]->MSCR[195]
#define PTG_PIN4_MSCR(slot)  prvVSIUL[slot]->MSCR[196]
#define PTG_PIN5_MSCR(slot)  prvVSIUL[slot]->MSCR[197]
#define PTG_PIN6_MSCR(slot)  prvVSIUL[slot]->MSCR[198]
#define PTG_PIN7_MSCR(slot)  prvVSIUL[slot]->MSCR[199]
#define PTG_PIN8_MSCR(slot)  prvVSIUL[slot]->MSCR[200]
#define PTG_PIN9_MSCR(slot)  prvVSIUL[slot]->MSCR[201]
#define PTG_PIN10_MSCR(slot) prvVSIUL[slot]->MSCR[202]
#define PTG_PIN11_MSCR(slot) prvVSIUL[slot]->MSCR[203]
#define PTG_PIN12_MSCR(slot) prvVSIUL[slot]->MSCR[204]
#define PTG_PIN13_MSCR(slot) prvVSIUL[slot]->MSCR[205]
#define PTG_PIN14_MSCR(slot) prvVSIUL[slot]->MSCR[206]
#define PTG_PIN15_MSCR(slot) prvVSIUL[slot]->MSCR[207]
#define PTG_PIN16_MSCR(slot) prvVSIUL[slot]->MSCR[208]
#define PTG_PIN17_MSCR(slot) prvVSIUL[slot]->MSCR[209]
#define PTG_PIN18_MSCR(slot) prvVSIUL[slot]->MSCR[210]
#define PTG_PIN19_MSCR(slot) prvVSIUL[slot]->MSCR[211]
#define PTG_PIN20_MSCR(slot) prvVSIUL[slot]->MSCR[212]
#define PTG_PIN21_MSCR(slot) prvVSIUL[slot]->MSCR[213]
#define PTG_PIN22_MSCR(slot) prvVSIUL[slot]->MSCR[214]
#define PTG_PIN23_MSCR(slot) prvVSIUL[slot]->MSCR[215]
#define PTG_PIN24_MSCR(slot) prvVSIUL[slot]->MSCR[216]
#define PTG_PIN25_MSCR(slot) prvVSIUL[slot]->MSCR[217]
#define PTG_PIN26_MSCR(slot) prvVSIUL[slot]->MSCR[218]
#define PTG_PIN27_MSCR(slot) prvVSIUL[slot]->MSCR[219]

#endif /* __SIUL_PRIVATE_H */
