"""Automated Pre-Flight Hardware Sanity Handshake (IMP-10).

Performs comprehensive diagnostic validation of hardware communication, sense leads,
thermal sensors, and power MOSFET stages prior to test commencement to prevent
costly mid-run aborts or lab safety incidents.
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, List, Optional

from ..comm.packet_codec import BoardParamsTelemetry, CellDataTelemetry

logger = logging.getLogger("SingleCellCycler.Preflight")


class CheckStatus(Enum):
    PASS = "PASS"
    WARN = "WARN"
    FAIL = "FAIL"


@dataclass(slots=True)
class SanityCheckItem:
    """Individual hardware sanity evaluation result."""
    name: str
    status: CheckStatus
    measured: str
    expected: str
    message: str
    is_critical: bool = True
    __test__ = False


@dataclass
class PreflightReport:
    """Comprehensive diagnostic report generated by pre-flight checker."""
    checks: List[SanityCheckItem] = field(default_factory=list)
    cell_id: int = 1
    timestamp: float = field(default_factory=time.time)
    __test__ = False

    @property
    def passed(self) -> bool:
        """True if no checks resulted in FAIL."""
        return not any(c.status == CheckStatus.FAIL for c in self.checks)

    @property
    def has_warnings(self) -> bool:
        """True if any check produced a WARN."""
        return any(c.status == CheckStatus.WARN for c in self.checks)

    @property
    def passed_count(self) -> int:
        return sum(1 for c in self.checks if c.status == CheckStatus.PASS)

    @property
    def warning_count(self) -> int:
        return sum(1 for c in self.checks if c.status == CheckStatus.WARN)

    @property
    def failure_count(self) -> int:
        return sum(1 for c in self.checks if c.status == CheckStatus.FAIL)

    @property
    def total_count(self) -> int:
        return len(self.checks)

    @property
    def summary_text(self) -> str:
        """Concise summary string for status pills."""
        if self.passed and not self.has_warnings:
            return f"Pre-Flight: {self.passed_count}/{self.total_count} Passed"
        elif self.passed and self.has_warnings:
            return f"Pre-Flight: {self.passed_count}/{self.total_count} Passed ({self.warning_count} Warn)"
        else:
            return f"Pre-Flight: {self.failure_count} Failed ({self.passed_count}/{self.total_count})"

    @property
    def summary_badge_style(self) -> str:
        """CSS stylesheet for toolbar status pill."""
        if self.passed and not self.has_warnings:
            return (
                "background-color: #064e3b; color: #34d399; border: 1px solid #10b981; "
                "font-weight: 700; border-radius: 12px; padding: 3px 10px; font-size: 11px;"
            )
        elif self.passed and self.has_warnings:
            return (
                "background-color: #78350f; color: #fbbf24; border: 1px solid #f59e0b; "
                "font-weight: 700; border-radius: 12px; padding: 3px 10px; font-size: 11px;"
            )
        else:
            return (
                "background-color: #7f1d1d; color: #f87171; border: 1px solid #ef4444; "
                "font-weight: 700; border-radius: 12px; padding: 3px 10px; font-size: 11px;"
            )

    def get_critical_failures(self) -> List[SanityCheckItem]:
        return [c for c in self.checks if c.status == CheckStatus.FAIL and c.is_critical]

    def get_warnings(self) -> List[SanityCheckItem]:
        return [c for c in self.checks if c.status == CheckStatus.WARN]

    def to_formatted_text(self) -> str:
        """Human-readable multi-line report for logging or diagnostics."""
        lines = [
            f"=== Pre-Flight Hardware Sanity Handshake (Cell {self.cell_id}) ===",
            f"Status: {'PASSED' if self.passed else 'FAILED'} | Checks: {self.passed_count}/{self.total_count} OK",
        ]
        for c in self.checks:
            icon = "✓" if c.status == CheckStatus.PASS else ("⚠" if c.status == CheckStatus.WARN else "✗")
            lines.append(f"[{icon} {c.status.value}] {c.name}: {c.measured} (Expected: {c.expected}) -> {c.message}")
        return "\n".join(lines)


class PreflightSanityChecker:
    """Pre-flight sanity diagnostic engine validating hardware readiness."""

    def __init__(
        self,
        max_telemetry_age_s: float = 1.5,
        max_thermal_parity_delta_c: float = 4.0,
        thermal_parity_warn_c: float = 6.0,
        min_cell_voltage_v: float = 0.50,
        max_cell_voltage_v: float = 4.55,
        max_idle_leakage_current_a: float = 0.050,
        idle_leakage_warn_a: float = 0.150,
    ):
        self.max_telemetry_age_s = max_telemetry_age_s
        self.max_thermal_parity_delta_c = max_thermal_parity_delta_c
        self.thermal_parity_warn_c = thermal_parity_warn_c
        self.min_cell_voltage_v = min_cell_voltage_v
        self.max_cell_voltage_v = max_cell_voltage_v
        self.max_idle_leakage_current_a = max_idle_leakage_current_a
        self.idle_leakage_warn_a = idle_leakage_warn_a

    def evaluate(
        self,
        cell_data: Optional[CellDataTelemetry],
        board_params: Optional[BoardParamsTelemetry],
        readbacks: Dict[int, int],
        last_telemetry_age_s: Optional[float],
        cell_id: int = 1,
        chemistry_name: str = "Standard",
        chemistry_min_v: float = 2.50,
        chemistry_max_v: float = 4.25,
    ) -> PreflightReport:
        """Perform comprehensive 4-dimension sanity evaluation."""
        report = PreflightReport(cell_id=cell_id, timestamp=time.time())

        # -------------------------------------------------------------
        # 1. Telemetry Link & Communication Latency
        # -------------------------------------------------------------
        if cell_data is None or last_telemetry_age_s is None:
            report.checks.append(
                SanityCheckItem(
                    name="Telemetry Link & Latency",
                    status=CheckStatus.FAIL,
                    measured="Offline",
                    expected="< 1.0 s",
                    message="No telemetry frames received from MCU. Ensure USB/serial cable is connected and board is powered.",
                    is_critical=True,
                )
            )
        elif last_telemetry_age_s > 2.5:
            report.checks.append(
                SanityCheckItem(
                    name="Telemetry Link & Latency",
                    status=CheckStatus.FAIL,
                    measured=f"{last_telemetry_age_s:.2f} s",
                    expected="< 1.0 s",
                    message=f"Serial link timed out ({last_telemetry_age_s:.2f}s elapsed since last packet).",
                    is_critical=True,
                )
            )
        elif last_telemetry_age_s > self.max_telemetry_age_s:
            report.checks.append(
                SanityCheckItem(
                    name="Telemetry Link & Latency",
                    status=CheckStatus.WARN,
                    measured=f"{last_telemetry_age_s * 1000:.0f} ms",
                    expected="< 1000 ms",
                    message=f"Elevated UART packet latency ({last_telemetry_age_s:.2f}s).",
                    is_critical=False,
                )
            )
        else:
            latency_ms = max(1.0, last_telemetry_age_s * 1000)
            report.checks.append(
                SanityCheckItem(
                    name="Telemetry Link & Latency",
                    status=CheckStatus.PASS,
                    measured=f"{latency_ms:.0f} ms",
                    expected="< 1000 ms",
                    message="Serial link active and synchronized at nominal 10 Hz rate.",
                    is_critical=True,
                )
            )

        # If link is completely dead, populate remaining checks as FAIL and return
        if cell_data is None:
            report.checks.extend([
                SanityCheckItem(
                    name="Cell Sense Lead Voltage",
                    status=CheckStatus.FAIL,
                    measured="N/A",
                    expected="0.500 V – 4.500 V",
                    message="Cannot sample voltage without active telemetry link.",
                    is_critical=True,
                ),
                SanityCheckItem(
                    name="Thermistor Parity & Health",
                    status=CheckStatus.FAIL,
                    measured="N/A",
                    expected="ΔT ≤ 4.0 °C",
                    message="Cannot sample temperatures without active telemetry link.",
                    is_critical=True,
                ),
                SanityCheckItem(
                    name="Idle MOSFET & Leakage Current",
                    status=CheckStatus.FAIL,
                    measured="N/A",
                    expected="|I| ≤ 0.050 A",
                    message="Cannot verify quiescent bus state without telemetry link.",
                    is_critical=True,
                ),
            ])
            return report

        # -------------------------------------------------------------
        # 2. Cell Sense Lead Continuity & Voltage Range
        # -------------------------------------------------------------
        voltage = cell_data.voltage
        if voltage < self.min_cell_voltage_v:
            report.checks.append(
                SanityCheckItem(
                    name="Cell Sense Lead Voltage",
                    status=CheckStatus.FAIL,
                    measured=f"{voltage:.3f} V",
                    expected=f"≥ {self.min_cell_voltage_v:.3f} V",
                    message=(
                        f"Detected 0.00V / floating Kelvin sense lead ({voltage:.3f} V). "
                        "Verify battery connection and terminal clamps before starting."
                    ),
                    is_critical=True,
                )
            )
        elif voltage > self.max_cell_voltage_v:
            report.checks.append(
                SanityCheckItem(
                    name="Cell Sense Lead Voltage",
                    status=CheckStatus.FAIL,
                    measured=f"{voltage:.3f} V",
                    expected=f"≤ {self.max_cell_voltage_v:.3f} V",
                    message=f"Voltage {voltage:.3f} V exceeds cycler hardware ADC upper ceiling ({self.max_cell_voltage_v:.2f} V).",
                    is_critical=True,
                )
            )
        elif voltage > chemistry_max_v + 0.15:
            report.checks.append(
                SanityCheckItem(
                    name="Cell Sense Lead Voltage",
                    status=CheckStatus.WARN,
                    measured=f"{voltage:.3f} V",
                    expected=f"≤ {chemistry_max_v:.2f} V ({chemistry_name})",
                    message=f"Cell voltage exceeds {chemistry_name} full-charge ceiling ({chemistry_max_v:.2f} V).",
                    is_critical=False,
                )
            )
        elif voltage < chemistry_min_v - 0.20:
            report.checks.append(
                SanityCheckItem(
                    name="Cell Sense Lead Voltage",
                    status=CheckStatus.WARN,
                    measured=f"{voltage:.3f} V",
                    expected=f"≥ {chemistry_min_v:.2f} V ({chemistry_name})",
                    message=f"Deeply discharged cell ({voltage:.3f} V < {chemistry_min_v:.2f} V). Low-current pre-charge recommended.",
                    is_critical=False,
                )
            )
        else:
            report.checks.append(
                SanityCheckItem(
                    name="Cell Sense Lead Voltage",
                    status=CheckStatus.PASS,
                    measured=f"{voltage:.3f} V",
                    expected=f"{self.min_cell_voltage_v:.2f} V – {chemistry_max_v:.2f} V",
                    message=f"Cell voltage is stable and within nominal operational window for {chemistry_name}.",
                    is_critical=True,
                )
            )

        # -------------------------------------------------------------
        # 3. Thermistor Parity & Thermal Probe Integrity
        # -------------------------------------------------------------
        t_term = cell_data.terminal_temp
        t_body = cell_data.body_temp
        t_amb = board_params.ambient_temp if board_params else None

        # Check absolute bounds (disconnected thermistors read ≤ 0°C or open ADC max > 100°C)
        if t_term <= 0.0 or t_body <= 0.0 or (t_amb is not None and t_amb <= 0.0):
            report.checks.append(
                SanityCheckItem(
                    name="Thermistor Parity & Health",
                    status=CheckStatus.FAIL,
                    measured=f"Term: {t_term:.1f}°C | Body: {t_body:.1f}°C" + (f" | Amb: {t_amb:.1f}°C" if t_amb else ""),
                    expected="> 5.0 °C",
                    message="Open-circuit or cold-fault thermistor reading detected (≤ 0.0°C). Check probe wiring.",
                    is_critical=True,
                )
            )
        elif t_term >= 55.0 or t_body >= 55.0:
            report.checks.append(
                SanityCheckItem(
                    name="Thermistor Parity & Health",
                    status=CheckStatus.FAIL,
                    measured=f"Term: {t_term:.1f}°C | Body: {t_body:.1f}°C",
                    expected="< 45.0 °C (Idle)",
                    message="Cell temperature is dangerously high before test initiation (> 55°C). Inspect cell immediately.",
                    is_critical=True,
                )
            )
        else:
            # Check parity delta
            delta_cell = abs(t_term - t_body)
            delta_amb = max(abs(t_term - t_amb), abs(t_body - t_amb)) if t_amb is not None else 0.0
            max_delta = max(delta_cell, delta_amb)

            if delta_cell > self.thermal_parity_warn_c or delta_amb > (self.thermal_parity_warn_c + 2.0):
                report.checks.append(
                    SanityCheckItem(
                        name="Thermistor Parity & Health",
                        status=CheckStatus.FAIL,
                        measured=f"ΔT = {max_delta:.1f} °C (Term: {t_term:.1f}°C, Body: {t_body:.1f}°C" + (f", Amb: {t_amb:.1f}°C" if t_amb else "") + ")",
                        expected=f"ΔT ≤ {self.max_thermal_parity_delta_c:.1f} °C",
                        message="Excessive thermal probe mismatch at idle rest. Probe detached, uncalibrated, or noisy.",
                        is_critical=True,
                    )
                )
            elif delta_cell > self.max_thermal_parity_delta_c:
                report.checks.append(
                    SanityCheckItem(
                        name="Thermistor Parity & Health",
                        status=CheckStatus.WARN,
                        measured=f"ΔT = {delta_cell:.1f} °C",
                        expected=f"ΔT ≤ {self.max_thermal_parity_delta_c:.1f} °C",
                        message=f"Moderate temperature disparity between terminal and body probes ({delta_cell:.1f}°C).",
                        is_critical=False,
                    )
                )
            else:
                report.checks.append(
                    SanityCheckItem(
                        name="Thermistor Parity & Health",
                        status=CheckStatus.PASS,
                        measured=f"ΔT = {delta_cell:.1f} °C (Term: {t_term:.1f}°C, Body: {t_body:.1f}°C)",
                        expected=f"ΔT ≤ {self.max_thermal_parity_delta_c:.1f} °C",
                        message="Terminal and body thermistor probes are in thermal equilibrium with ambient.",
                        is_critical=True,
                    )
                )

        # -------------------------------------------------------------
        # 4. Idle MOSFET De-Energization & Quiescent Leakage Current
        # -------------------------------------------------------------
        current = cell_data.current
        abs_current = abs(current)
        chg_byte = readbacks.get(0x6002, 0)
        dis_byte = readbacks.get(0x6003, 0)
        loads_byte = readbacks.get(0x6004, 0)

        is_power_stage_active = (chg_byte & 0x01) or (dis_byte & 0x01) or (loads_byte != 0)

        if abs_current > self.idle_leakage_warn_a:
            report.checks.append(
                SanityCheckItem(
                    name="Idle MOSFET & Leakage Current",
                    status=CheckStatus.FAIL,
                    measured=f"I = {current:+.3f} A",
                    expected=f"|I| ≤ {self.max_idle_leakage_current_a:.3f} A",
                    message="Significant current detected at idle! Possible shorted power MOSFET or stuck relay.",
                    is_critical=True,
                )
            )
        elif is_power_stage_active:
            report.checks.append(
                SanityCheckItem(
                    name="Idle MOSFET & Leakage Current",
                    status=CheckStatus.FAIL,
                    measured=f"Chg: 0x{chg_byte:02X} | Dis: 0x{dis_byte:02X} | Load: 0x{loads_byte:02X}",
                    expected="All 0x00 (Safe Idle)",
                    message="Charge or discharge stages are energized while cycler is in idle state. Sending safe zero.",
                    is_critical=True,
                )
            )
        elif abs_current > self.max_idle_leakage_current_a:
            report.checks.append(
                SanityCheckItem(
                    name="Idle MOSFET & Leakage Current",
                    status=CheckStatus.WARN,
                    measured=f"I = {current:+.3f} A",
                    expected=f"|I| ≤ {self.max_idle_leakage_current_a:.3f} A",
                    message="Minor residual current offset at idle. Zero-current calibration advised.",
                    is_critical=False,
                )
            )
        else:
            report.checks.append(
                SanityCheckItem(
                    name="Idle MOSFET & Leakage Current",
                    status=CheckStatus.PASS,
                    measured=f"I = {current:+.3f} A (Idle)",
                    expected=f"|I| ≤ {self.max_idle_leakage_current_a:.3f} A",
                    message="All power stages disengaged; zero quiescent leakage verified.",
                    is_critical=True,
                )
            )

        return report
