/*
 * Copyright 2018-2020, 2024 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * @file      mcme_private.h
 * @brief     Mode Entry Module (MCME) private definitions.
 */
#ifndef __MCME_PRIVATE_H
#define __MCME_PRIVATE_H

/* PRTN0_COFB1_CLKEN Bit Fields */
#define MCME_TRGMUX   (0x1U << 0)  ///< Trigger Multiplexing Control (PRTN0_COFB1)
#define MCME_BCTU     (0x1U << 1)  ///< Body Cross Triggering Unit (PRTN0_COFB1)
#define MCME_EMIOS0   (0x1U << 2)  ///< EMIOS 0 (PRTN0_COFB1)
#define MCME_EMIOS1   (0x1U << 3)  ///< EMIOS 1 (PRTN0_COFB1)
#define MCME_EMIOS2   (0x1U << 4)  ///< EMIOS 2 (PRTN0_COFB1)
#define MCME_LCU0     (0x1U << 6)  ///< Logic Control Unit 0 (PRTN0_COFB1)
#define MCME_LCU1     (0x1U << 7)  ///< Logic Control Unit 1 (PRTN0_COFB1)
#define MCME_ADC0     (0x1U << 8)  ///< Analog-to-digital converter 0 (PRTN0_COFB1)
#define MCME_ADC1     (0x1U << 9)  ///< Analog-to-digital converter 1 (PRTN0_COFB1)
#define MCME_ADC2     (0x1U << 10) ///< Analog-to-digital converter 2 (PRTN0_COFB1)
#define MCME_PIT0     (0x1U << 12) ///< Programmable Interrupt Timer 0 (PRTN0_COFB1)
#define MCME_PIT1     (0x1U << 13) ///< Programmable Interrupt Timer 1 (PRTN0_COFB1)
#define MCME_MUA      (0x1U << 14) ///< MU_A (PRTN0_COFB1)
#define MCME_MUB      (0x1U << 15) ///< MU_B (PRTN0_COFB1)
#define MCME_I3C0     (0x1U << 16) ///< I3C0 (PRTN0_COFB1)
/* PRTN1_COFB0_CLKEN Bit Fields */
#define MCME_EDMA     (0x1U << 3)  ///< EDMA control & status (MP_CSR; MP_ES; MP_HRS) (PRTN1_COFB0)
#define MCME_TCD0     (0x1U << 4)  ///< EDMA transfer control descriptor 0 (PRTN1_COFB0)
#define MCME_TCD1     (0x1U << 5)  ///< EDMA transfer control descriptor 1 (PRTN1_COFB0)
#define MCME_TCD2     (0x1U << 6)  ///< EDMA transfer control descriptor 2 (PRTN1_COFB0)
#define MCME_TCD3     (0x1U << 7)  ///< EDMA transfer control descriptor 3 (PRTN1_COFB0)
#define MCME_TCD4     (0x1U << 8)  ///< EDMA transfer control descriptor 4 (PRTN1_COFB0)
#define MCME_TCD5     (0x1U << 9)  ///< EDMA transfer control descriptor 5 (PRTN1_COFB0)
#define MCME_TCD6     (0x1U << 10) ///< EDMA transfer control descriptor 6 (PRTN1_COFB0)
#define MCME_TCD7     (0x1U << 11) ///< EDMA transfer control descriptor 7 (PRTN1_COFB0)
#define MCME_TCD8     (0x1U << 12) ///< EDMA transfer control descriptor 8 (PRTN1_COFB0)
#define MCME_TCD9     (0x1U << 13) ///< EDMA transfer control descriptor 9 (PRTN1_COFB0)
#define MCME_TCD10    (0x1U << 14) ///< EDMA transfer control descriptor 10 (PRTN1_COFB0)
#define MCME_TCD11    (0x1U << 15) ///< EDMA transfer control descriptor 11 (PRTN1_COFB0)
#define MCME_SDA      (0x1U << 21) ///< SDA-AP (PRTN1_COFB0)
#define MCME_EIM      (0x1U << 22) ///< EIM (PRTN1_COFB0)
#define MCME_ERM      (0x1U << 23) ///< ERM (PRTN1_COFB0)
#define MCME_MSCM     (0x1U << 24) ///< MSCM (PRTN1_COFB0)
#define MCME_SWT0     (0x1U << 28) ///< Software Watchdog 0 (PRTN1_COFB0)
#define MCME_STM0     (0x1U << 29) ///< System Timer Module 0 (PRTN1_COFB0)
#define MCME_INTM     (0x1U << 31) ///< Interrupt Monitor (PRTN1_COFB0)
/* PRTN1_COFB1_CLKEN Bit Fields */
#define MCME_DMAMUX0  (0x1U << 0)  ///< DMA Channel Multiplexer 0 (PRTN1_COFB1)
#define MCME_DMAMUX1  (0x1U << 1)  ///< DMA Channel Multiplexer 1 (PRTN1_COFB1)
#define MCME_RTC      (0x1U << 2)  ///< Real-time clock (PRTN1_COFB1)
#define MCME_VWRAP    (0x1U << 10) ///< SIUL2_VIRTWRAPPER (PRTN1_COFB1)
#define MCME_WKPU     (0x1U << 13) ///< Wakeup Unit (PRTN1_COFB1)
#define MCME_CMU05    (0x1U << 15) ///< CMU 0-5 (PRTN1_COFB1)
#define MCME_TSPC     (0x1U << 17) ///< Touch Sensing Coupling Controller (PRTN1_COFB1)
#define MCME_SXOSC    (0x1U << 19) ///< 32 kHz Slow External Crystal Oscillator (PRTN1_COFB1)
#define MCME_FXOSC    (0x1U << 21) ///< 8-40 MHz Fast External Crystal Oscillator (PRTN1_COFB1)
#define MCME_PLL      (0x1U << 24) ///< Frequency Modulated Phase-Locked Loop (PRTN1_COFB1)
#define MCME_PIT2     (0x1U << 31) ///< Programmable Interrupt Timer 2 (PRTN1_COFB1)
/* PRTN1_COFB2_CLKEN Bit Fields */
#define MCME_FCAN0    (0x1U << 1)  ///< FlexCAN 0 (PRTN1_COFB2)
#define MCME_FCAN1    (0x1U << 2)  ///< FlexCAN 1 (PRTN1_COFB2)
#define MCME_FCAN2    (0x1U << 3)  ///< FlexCAN 2 (PRTN1_COFB2)
#define MCME_FCAN3    (0x1U << 4)  ///< FlexCAN 3 (PRTN1_COFB2)
#define MCME_FCAN4    (0x1U << 5)  ///< FlexCAN 4 (PRTN1_COFB2)
#define MCME_FCAN5    (0x1U << 6)  ///< FlexCAN 5 (PRTN1_COFB2)
#define MCME_FLEXIO   (0x1U << 9)  ///< Flexible IO (PRTN1_COFB2)
#define MCME_LPUART0  (0x1U << 10) ///< Low Power UART 0 (PRTN1_COFB2)
#define MCME_LPUART1  (0x1U << 11) ///< Low Power UART 1 (PRTN1_COFB2)
#define MCME_LPUART2  (0x1U << 12) ///< Low Power UART 2 (PRTN1_COFB2)
#define MCME_LPUART3  (0x1U << 13) ///< Low Power UART 3 (PRTN1_COFB2)
#define MCME_LPUART4  (0x1U << 14) ///< Low Power UART 4 (PRTN1_COFB2)
#define MCME_LPUART5  (0x1U << 15) ///< Low Power UART 5 (PRTN1_COFB2)
#define MCME_LPUART6  (0x1U << 16) ///< Low Power UART 6 (PRTN1_COFB2)
#define MCME_LPUART7  (0x1U << 17) ///< Low Power UART 7 (PRTN1_COFB2)
#define MCME_LPI2C0   (0x1U << 20) ///< Low Power I2C 0 (PRTN1_COFB2)
#define MCME_LPI2C1   (0x1U << 21) ///< Low Power I2C 1 (PRTN1_COFB2)
#define MCME_LPSPI0   (0x1U << 22) ///< Low Power SPI 0 (PRTN1_COFB2)
#define MCME_LPSPI1   (0x1U << 23) ///< Low Power SPI 1 (PRTN1_COFB2)
#define MCME_LPSPI2   (0x1U << 24) ///< Low Power SPI 2 (PRTN1_COFB2)
#define MCME_LPSPI3   (0x1U << 25) ///< Low Power SPI 3 (PRTN1_COFB2)
#define MCME_SAI0     (0x1U << 27) ///< Synchronous Audio Interface 0 (PRTN1_COFB2)
#define MCME_LPCMP0   (0x1U << 28) ///< Low Power CMP 0 (PRTN1_COFB2)
#define MCME_LPCMP1   (0x1U << 29) ///< Low Power CMP 1 (PRTN1_COFB2)
#define MCME_TMU      (0x1U << 31) ///< TMU Temperature Sensor Unit (PRTN1_COFB2)
/* PRTN1_COFB3_CLKEN Bit Fields */
#define MCME_CRC      (0x1U << 0)  ///< CRC (PRTN1_COFB3)
/* PRTN2_COFB0_CLKEN Bit Fields */
#define MCME_TCD12    (0x1U << 4)  ///< EDMA transfer control descriptor 12 (PRTN2_COFB0)
#define MCME_TCD13    (0x1U << 5)  ///< EDMA transfer control descriptor 13 (PRTN2_COFB0)
#define MCME_TCD14    (0x1U << 6)  ///< EDMA transfer control descriptor 14 (PRTN2_COFB0)
#define MCME_TCD15    (0x1U << 7)  ///< EDMA transfer control descriptor 15 (PRTN2_COFB0)
#define MCME_TCD16    (0x1U << 8)  ///< EDMA transfer control descriptor 16 (PRTN2_COFB0)
#define MCME_TCD17    (0x1U << 9)  ///< EDMA transfer control descriptor 17 (PRTN2_COFB0)
#define MCME_TCD18    (0x1U << 10) ///< EDMA transfer control descriptor 18 (PRTN2_COFB0)
#define MCME_TCD19    (0x1U << 11) ///< EDMA transfer control descriptor 19 (PRTN2_COFB0)
#define MCME_TCD20    (0x1U << 12) ///< EDMA transfer control descriptor 20 (PRTN2_COFB0)
#define MCME_TCD21    (0x1U << 13) ///< EDMA transfer control descriptor 21 (PRTN2_COFB0)
#define MCME_TCD22    (0x1U << 14) ///< EDMA transfer control descriptor 22 (PRTN2_COFB0)
#define MCME_TCD23    (0x1U << 15) ///< EDMA transfer control descriptor 23 (PRTN2_COFB0)
#define MCME_TCD24    (0x1U << 16) ///< EDMA transfer control descriptor 24 (PRTN2_COFB0)
#define MCME_TCD25    (0x1U << 17) ///< EDMA transfer control descriptor 25 (PRTN2_COFB0)
#define MCME_TCD26    (0x1U << 18) ///< EDMA transfer control descriptor 26 (PRTN2_COFB0)
#define MCME_TCD27    (0x1U << 19) ///< EDMA transfer control descriptor 27 (PRTN2_COFB0)
#define MCME_TCD28    (0x1U << 20) ///< EDMA transfer control descriptor 28 (PRTN2_COFB0)
#define MCME_TCD29    (0x1U << 21) ///< EDMA transfer control descriptor 29 (PRTN2_COFB0)
#define MCME_TCD30    (0x1U << 22) ///< EDMA transfer control descriptor 30 (PRTN2_COFB0)
#define MCME_TCD31    (0x1U << 23) ///< EDMA transfer control descriptor 31 (PRTN2_COFB0)
#define MCME_SEMA42   (0x1U << 24) ///< Semaphores2 (PRTN2_COFB0)
#define MCME_SWT1     (0x1U << 27) ///< Software Watchdog 1 (PRTN2_COFB0)
#define MCME_STM1     (0x1U << 29) ///< System Timer Module 1 (PRTN2_COFB0)
/* PRTN2_COFB1_CLKEN Bit Fields */
#define MCME_ENET     (0x1U << 0)  ///< ENET (PRTN2_COFB1)
#define MCME_LPUART8  (0x1U << 3)  ///< Low Power UART 8 (PRTN2_COFB1)
#define MCME_LPUART9  (0x1U << 4)  ///< Low Power UART 9 (PRTN2_COFB1)
#define MCME_LPUART10 (0x1U << 5)  ///< Low Power UART 10 (PRTN2_COFB1)
#define MCME_LPUART11 (0x1U << 6)  ///< Low Power UART 11 (PRTN2_COFB1)
#define MCME_LPUART12 (0x1U << 7)  ///< Low Power UART 12 (PRTN2_COFB1)
#define MCME_LPUART13 (0x1U << 8)  ///< Low Power UART 13 (PRTN2_COFB1)
#define MCME_LPUART14 (0x1U << 9)  ///< Low Power UART 14 (PRTN2_COFB1)
#define MCME_LPUART15 (0x1U << 10) ///< Low Power UART 15 (PRTN2_COFB1)
#define MCME_LPSPI4   (0x1U << 15) ///< Low Power SPI 4 (PRTN2_COFB1)
#define MCME_LPSPI5   (0x1U << 16) ///< Low Power SPI 5 (PRTN2_COFB1)
#define MCME_QUADSPI  (0x1U << 19) ///< QuadSPI (PRTN2_COFB1)
#define MCME_SAI1     (0x1U << 23) ///< Synchronous Audio Interface 1 (PRTN2_COFB1)
#define MCME_LPCMP2   (0x1U << 26) ///< Low Power CMP 2 (PRTN2_COFB1)
#define MCME_TCMCORE0 (0x1U << 30) ///< Core0 TCM (PRTN2_COFB1)
#define MCME_TCMCORE1 (0x1U << 31) ///< Core1 TCM (PRTN2_COFB1)

#endif /* __MCME_PRIVATE_H */
